NVIDIA-NeMo/Guardrails

nemoguardrails/streaming.py

Fixes the issue with the latest version of LangChain.

Fix ChatGenerationChunk issue.

---

nemoguardrails/kb/kb.py

Fix annoy import, to allow using without.

---

nemoguardrails/rails/llm/llmrails.py
tests/test_bug_5.py

Fix #209: user messages were missing from prompt.

---

nemoguardrails/embeddings/cache.py
nemoguardrails/rails/llm/llmrails.py
nemoguardrails/server/api.py
nemoguardrails/utils.py
tests/test_sync_generate_no_event_loop.py

See individual commits for more details.

Fix multi-config bug, asyncio loop issue and cache folder for embeddings.

---

.gitignore
nemoguardrails/logging/processing_log.py
nemoguardrails/rails/llm/llm_flows.co
pyproject.toml
tests/test_input_rails_only.py

Thanks @trebedea for pointing this out.

Fix the incorrect logging of an extra dialog rail

---

nemoguardrails/rails/llm/config.py

Some recent updates undid a change to folder walk to follow symlinks. This PR re-merges that change to the new code.

Redo followlinks PR in new code.

---

nemoguardrails/logging/callbacks.py

Fix #378 - missing prompt in verbose mode for chat models.

Fix #378 - missing prompt in verbose mode for chat models

---

nemoguardrails/logging/callbacks.py

Fix #411 - explain rails not working for chat models

Fix #411 - explain rails not working for chat models

---

nemoguardrails/rails/llm/llm_flows.co

I noticed a small typo in llm_flows.co file. It is not a big deal but better be fixed. 
Only a comment section is altered, thus this can be a quick merge.

Typo fix: Comment in llm_flows.co

---

CHANGELOG.md
nemoguardrails/integrations/langchain/runnable_rails.py
tests/test_runnable_rails.py

* Expose `LLMRails` `verbose` argument in `RunnableRails`
* Add simple unit test

Expose verbose arg in RunnableRails

---

nemoguardrails/library/hallucination/flows.co

Fix typo for hallucination message.

---

docs/research.md

Added the first version of the research roadmap for guardrails.

Research roadmap for guardrails

---

docs/user_guides/llm/nvidia_ai_endpoints/README.md
docs/user_guides/llm/nvidia_ai_endpoints/nvidia_ai_endpoints_models.ipynb

Update the documentation for NVIDIA AI Catalog to the new naming convention.

Update documentation for NVIDIA AI Endpoints.

---

.gitignore
nemoguardrails/colang/v2_x/lang/expansion.py

Trying my first PR on your project. Adding element name and line number to colang 2.0 syntax error message.

Add colang 2.0 syntax error details

---

nemoguardrails/actions/action_dispatcher.py
nemoguardrails/actions/llm/generation.py
nemoguardrails/actions/llm/utils.py
nemoguardrails/colang/v1_0/runtime/flows.py
nemoguardrails/context.py
nemoguardrails/rails/llm/config.py
nemoguardrails/rails/llm/llmrails.py
tests/test_runnable_rails.py

A set of updates and fixes needed for the microservice.

Feature/ms 24.06

---

nemoguardrails/colang/v2_x/lang/expansion.py
nemoguardrails/colang/v2_x/library/avatars.co
nemoguardrails/colang/v2_x/library/llm.co
nemoguardrails/colang/v2_x/runtime/flows.py
nemoguardrails/colang/v2_x/runtime/statemachine.py
tests/test_configs/multi_modal_demo_v2_x/demo.co
tests/test_configs/multi_modal_demo_v2_x/show_cases/show_case_number_guessing_game.co
tests/test_configs/multi_modal_demo_v2_x/show_cases/show_case_proactive_turn_taking.co
tests/v2_x/test_flow_mechanics.py

Fixes the flow activation mechanism such that flows can only be activated once and remain being activated until all activations have ended.
Related changes:
* Fix of activation expansion
* Removal of unnecessary context attributes
* Adapting multimodal demo to new activation mechanism

Fix Colang 2 flow activation

---

nemoguardrails/utils.py

Adds the modality info to support FacialGestureBotAction.

Add support for FacialGestureBotAction

---

nemoguardrails/llm/prompts/general.yml

This PR changes the default templates to a more verbose version which is more robust, especially with smaller LLMs.

Change default templates

---

nemoguardrails/actions/llm/generation.py
nemoguardrails/llm/prompts/unknown.yml
tests/test_configs/multi_step_generation/config.yml
tests/test_streaming.py
tests/utils.py

Follow-up fixes for the default prompt change.

---

nemoguardrails/colang/v2_x/runtime/serialization.py
nemoguardrails/rails/llm/config.py

Fix an issue with the serialization of the state and a couple other smaller bugs.

Fix Colang 2.0 state serialization issue

---

CHANGELOG-Colang.md
CHANGELOG.md

- Add all the changes merged so far to CHANGELOG
- Move all Colang-related changes to separate CHANGELOG-Colang for easier tracking.

Changelog update

---

CHANGELOG-Colang.md
docs/colang_2/language_reference/more-on-flows.rst
nemoguardrails/colang/v2_x/lang/expansion.py
nemoguardrails/colang/v2_x/lang/grammar/colang.lark
nemoguardrails/colang/v2_x/library/llm.co
nemoguardrails/colang/v2_x/runtime/statemachine.py
tests/test_configs/multi_modal_demo_v2_x/demo.co
tests/test_configs/multi_modal_demo_v2_x/show_cases/show_case_back_channelling_interaction.co
tests/v2_x/test_flow_mechanics.py
vscode_extension/colang-2-lang/syntaxes/colang.tmLanguage.json

Add support for the `deactivate <FLOW_ID>` keyword that is a shortcut for `StopFlow(flow_id="<FLOW_ID>", deactivate=True)`

Feature/colang 2/deactivate keyword

---

nemoguardrails/eval/models.py
nemoguardrails/rails/llm/config.py
nemoguardrails/server/api.py

Fix compatibility with Pydantic 1.10.x

refactor(api): Update Pydantic validators

---

nemoguardrails/cli/migration.py
nemoguardrails/rails/llm/config.py

change 'send event' to 'send' to fix support for rails exception in Colang 2.x

fix: change 'send event' to 'send'

---

nemoguardrails/actions/v2_x/generation.py

The logic needs to be improved, this is a quick solution.

Fix a small bug in the generate_flow action for Colang 2.

---

CHANGELOG-Colang.md
docs/colang_2/language_reference/working-with-variables-and-expressions.rst
nemoguardrails/colang/v2_x/runtime/eval.py
nemoguardrails/colang/v2_x/runtime/flows.py
nemoguardrails/colang/v2_x/runtime/runtime.py
nemoguardrails/colang/v2_x/runtime/serialization.py
nemoguardrails/colang/v2_x/runtime/statemachine.py
nemoguardrails/rails/llm/config.py
tests/test_configs/system_variable_access_v2/config.yml
tests/test_configs/system_variable_access_v2/system_variable_access_v2.co
tests/v2_x/test_state_serialization.py
tests/v2_x/test_system_variable_access.py

Exposes the bot configuration as variable `$system.config` in Colang 2

Feaure/colang 2/expose bot config

---

nemoguardrails/library/cleanlab/flows.co
nemoguardrails/library/cleanlab/flows.v1.co

Migrate cleanlab to colang 2 and add exception handling

feat(library): Migrate cleanlab to colang 2 and add exception handling

---

CHANGELOG-Colang.md
docs/colang_2/language_reference/more-on-flows.rst
nemoguardrails/colang/v2_x/lang/transformer.py
nemoguardrails/colang/v2_x/library/avatars.co
nemoguardrails/colang/v2_x/library/core.co
nemoguardrails/colang/v2_x/runtime/flows.py
nemoguardrails/colang/v2_x/runtime/statemachine.py
tests/v2_x/test_flow_mechanics.py

Add support for interaction loop flow priorities.

Feature/colang 2/interaction loop priorties

---

nemoguardrails/actions/v2_x/generation.py
nemoguardrails/colang/v2_x/lang/parser.py

This PR fixes the detection of the triggering flow id in `generate_flow` action.

Fix the detection of the triggering flow id

---

nemoguardrails/actions/v2_x/generation.py
tests/test_embeddings_only_user_messages.py

This PR adds support for embeddings only with search threshold and fallback intent.

feat: Add support for embeddings only with search threshold

---

README.md
nemoguardrails/__init__.py

chore: bump version to 0.10.1

---

nemoguardrails/actions/llm/generation.py
nemoguardrails/colang/v1_0/runtime/flows.py
nemoguardrails/colang/v1_0/runtime/runtime.py
nemoguardrails/colang/v2_x/lang/expansion.py
nemoguardrails/colang/v2_x/runtime/flows.py
nemoguardrails/colang/v2_x/runtime/runtime.py
nemoguardrails/colang/v2_x/runtime/statemachine.py
nemoguardrails/colang/v2_x/runtime/utils.py
nemoguardrails/utils.py

Unify uuid generation function calls such that the uuid are consistent for multiple runs in debug mode

Unify uuid generation functions

---

nemoguardrails/colang/v2_x/library/avatars.co

Colang 2.0 Standard Library Fix, that
* Resolves an issue with the avatar posture stuck in thinking state
* Adds an option for idle posture (when no user is present)

Fix posture management and include option for idling posture.

---

nemoguardrails/actions/llm/generation.py
nemoguardrails/actions/llm/utils.py

- Added skip_user_message parameter to get_retrieved_relevant_chunks function.
- Updated relevant_chunks assignment to handle cases with no user flow.

fix: update relevant_chunks retrieval logic

---

nemoguardrails/colang/v2_x/runtime/statemachine.py

Temporary fix for potential issues with the parent_uid being undefined.

Temporary fix for non existing parent_uid bug

---

nemoguardrails/library/utils/actions.py
nemoguardrails/utils.py
tests/utils.py
tests/v2_x/test_event_mechanics.py
tests/v2_x/test_python_api.py

Add better support for testing Colang 2 scripts with various (multimodal) events and multiple events at the same time.
@schuellc-nvidia , let me know if I should split the PR further.
- [ x ] I've read the [CONTRIBUTING](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/CONTRIBUTING.md) guidelines.
- [ x ] I've updated the documentation if applicable.
- [ x ] I've added tests if applicable.

Improved multi modal test support

---

nemoguardrails/actions/v2_x/generation.py
nemoguardrails/colang/v2_x/library/llm.co
tests/v2_x/test_llm_continuation.py

This fixes an issues to enable designing with undefined user intent flows such that they are awaited an triggered successfully if the flow 'continuation on undefined flow' is activated.

Fix/colang 2/fix undefined flow continuation

---

nemoguardrails/colang/v2_x/library/attention.co
nemoguardrails/library/attention/actions.py
tests/utils.py
tests/v2_x/test_attention_library.py

Add a new standard library module for handling user attention `attention.co` . This new module has the following features:
- If imported all user utterances are checked against the attention state of the user during that utterance. Unattentive utterances are ignored.
- Additional flows to help write Colang scripts that react to the user's attention level

Add attention module to Colang 2 library

---

docs/colang_2/overview.rst

Fixes a bug in the Colang documentation

Fix a bug in a code block

---

nemoguardrails/colang/v2_x/library/attention.co
tests/v2_x/test_attention_library.py

Address various small feedback for the attention.co Colang 2 library

Few minor fixes to `attention.co`

---

docs/user_guides/configuration-guide.md
examples/configs/tracing/README.md
examples/configs/tracing/config.yml
nemoguardrails/rails/llm/llmrails.py
nemoguardrails/tracing/adapters/opentelemetry.py

Enhancements to documentation and minor refactoring.

Feat: otel exporter

---

CHANGELOG-Colang.md
CHANGELOG.md
README.md
nemoguardrails/__init__.py

chore(changelog): update changelog for v0.11.0 release

---

CHANGELOG-Colang.md
CHANGELOG.md

Update date and fix a PR number

chore: update date changelog

---

vscode_extension/README.md

Improve VSCode extension installation instructions

Update colang extension install instructions

---

tests/test_configs/multi_modal_demo_v2_x/demo.co
tests/test_configs/multi_modal_demo_v2_x/demo.yml

Fix and improve multi modal demo

Fix and improve multi modal demo

---

.vscode/settings.json
CHANGELOG-Colang.md
CHANGELOG.md
README.md
docs/index.rst
nemoguardrails/rails/llm/config.py
pytest.ini

Update old underscore doc folder names

Update underscore folder names to new hyphen format

---

CHANGELOG-Colang.md

Fix GTP spelling

---

nemoguardrails/llm/prompts/llama3.yml

Add support for llama-3.2 models

---

nemoguardrails/colang/v2_x/runtime/statemachine.py
tests/v2_x/test_flow_mechanics.py

Adds the option to define the return value of a flow that is finished using the internal FinishFlow(return_value=X) event.

Add return_value to FinishFlow internal event

---

nemoguardrails/colang/v2_x/runtime/statemachine.py
tests/v2_x/test_flow_mechanics.py

Refactored #911 to use a more general context_update argument to change any context variable with a FinishFlow or StopFlow event.

Refactor return_value to context_update

---

docs/index.rst
docs/user-guides/advanced/index.rst
docs/user-guides/advanced/safeguarding-ai-virtual-assistant-blueprint.md

Update docs for build and some minor fixes (per #930 release).

chore(docs): update advanced user guides per v0.11.1 doc release

---

.gitlab-ci.yml

Poetry 2.0.0 is not backward compatible.

fix(ci): pin poetry version in gitlab ci

---

nemoguardrails/logging/callbacks.py

Token usage stats in LLM call info are broken for several LLMs: most chat models, all models when using streaming.
Current MR repairs most issues, now token usage stats works for:
- all chat models in non-streaming mode
- non-chat models from OpenAI in non-streaming mode
- all chat models in streaming mode
There is no easy fix for non-chat (legacy) models in streaming mode, even for OpenAI models, e.g. `gpt-3.5-turbo-instruct`. Access to token usage for these models, especially in streaming mode, is not standardized in Langchain.
- Fixes #947  
- [] I've updated the documentation if applicable.
- [] I've added tests if applicable.
- [] @mentions of the person or team responsible for reviewing proposed changes.

Fix: Repair token usage stats in LLM call info

---

.gitlab-ci.yml

Disable docs CI to troubleshoot.

Remove docs CI to troubleshoot

---

.gitlab-ci.yml
docs/conf.py

Work on my love-hate relationship with CI.  CI passes now.

chore(ci): Restore docs CI

---

nemoguardrails/library/factchecking/align_score/Dockerfile
nemoguardrails/library/factchecking/align_score/constraints.txt
nemoguardrails/library/factchecking/align_score/requirements.txt

Recent version of packages such as spacy is causing issue, this PR ensures the image can be built.

fix: fix alignscore dependency resolution in Dockerfile

---

nemoguardrails/library/factchecking/align_score/constraints.txt
nemoguardrails/library/factchecking/align_score/requirements.txt

Fix dependencies to resolve unecessary warning

fix: fix alignscore dependenices

---

.github/workflows/_test.yml
.github/workflows/latest-deps-tests.yml

Extend tests to use macOS and Windows to prevent issues like #1013

CI: Extend latest deps tests to use macOS and Windows

---

nemoguardrails/server/api.py

This PR aims to update the deprecated FastAPI lifecycle management @app.on_event to the new lifespan context manager @asynccontextmanager
- [Y] I've read the [CONTRIBUTING](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/CONTRIBUTING.md) guidelines.
- [Y] I've updated the documentation if applicable.
- [Y] I've added tests if applicable.
- [Y] @mentions of the person or team responsible for reviewing proposed changes.

replace FastAPI lifecycle management to use lifespan context manager

---

examples/configs/content_safety_vision/config.yml
examples/configs/content_safety_vision/prompts.yml
nemoguardrails/actions/llm/generation.py
nemoguardrails/llm/filters.py
nemoguardrails/llm/prompts.py
nemoguardrails/llm/prompts/openai-chatgpt.yml
nemoguardrails/llm/providers/providers.py
nemoguardrails/llm/taskmanager.py
nemoguardrails/logging/callbacks.py
nemoguardrails/rails/llm/llmrails.py
nemoguardrails/rails/llm/utils.py
tests/test_filters.py
tests/test_llm_task_manager_multimodal.py

- Add support for multimodal content (images + text) in input and output guardrails
- Enhance filters and text processing to properly handle multimodal messages with image_url content
- Add content safety vision configuration example for detecting unsafe content in images/text combinations
- Support both direct URL and base64 encoded images via image_url type
Import necessary packages and add some utilities:
```python
import base64
import requests
import urllib.request
from nemoguardrails import RailsConfig
from nemoguardrails.rails.llm.llmrails import LLMRails
from PIL import Image
import io
def download_image(url, filename):
"""
Download an image from a URL and save it to a file.
Args:
url (str): The URL of the image to download
filename (str): The filename to save the image to
"""
try: …
```

Feat: Support multimodal input and output rails

---

docs/user-guides/configuration-guide.md

Monika asked me to revise the reasoning model info.

docs: revise reasoning model info

---

docs/getting-started.md
docs/index.md
examples/configs/gs_content_safety/config/config.yml
examples/configs/gs_content_safety/config/prompts.yml
examples/configs/gs_content_safety/demo-out.txt
examples/configs/gs_content_safety/demo.py

Need to check with Monika, but I think she wants a simpler GS experience that uses the NemoGuard microservices.

docs: Consider new GS experience

---

nemoguardrails/__init__.py

- dynamically set version using importlib.metadata
- we prefer version defined in pyproject.toml

feat: dynamically set version using importlib.metadata

---

poetry.lock
pyproject.toml

Update to the latest version of the docs theme.

chore(deps): update NVIDIA theme for Sphinx

---

examples/configs/topic_safety/prompts.yml

Add additional rule to the topic control example guideline to allow for chit-chat and small talk.
NA
- [x ] I've read the [CONTRIBUTING](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/CONTRIBUTING.md) guidelines.
- [x ] I've updated the documentation if applicable.
- [ x] I've added tests if applicable.
- [ x] @mentions of the person or team responsible for reviewing proposed changes.

Change topic following prompt to allow chitchat

---

examples/configs/llm/hf_pipeline_dolly/config.py
examples/configs/llm/hf_pipeline_falcon/config.py
examples/configs/llm/hf_pipeline_llama2/config.py
examples/configs/llm/hf_pipeline_mosaic/config.py
examples/configs/llm/hf_pipeline_vicuna/config.py
examples/configs/rag/multi_kb/config.py
nemoguardrails/llm/providers/huggingface/__init__.py
nemoguardrails/llm/providers/huggingface/pipeline.py

Move `HuggingFacePipelineCompatible` to dedicated provider module under huggingface package and update import paths across example configs.

refactor(llm): reorganize HuggingFace provider structure

---

tests/test_tracing.py

style: apply pre-commit hooks

---

.github/workflows/full-tests.yml
.github/workflows/latest-deps-tests.yml
.github/workflows/pr-tests.yml
.github/workflows/test-and-build-wheel.yml

This PR ensures that workflows have clear and distinct purposes:
1. **PR Tests** (`pr-tests.yml`):
- Fast feedback on PRs
- Linux only testing
- Runs on all PR events
- Purpose: quick PR validation
2. **Full Tests** (`full-tests.yml`):
- Cross platform testing (Windows, macOS)
- Runs on:
- PR review events
- Pushes to main/develop
- Tags
- Manual dispatch
- Purpose: comprehensive platform coverage
3. **Build and Test Distribution** (`test-and-build-wheel.yml`):
- Builds and tests wheel distributions
- Runs on:
- Pushes to main/develop
- Tags
- Daily schedule
- Purpose: build and release validation
We get:
1. Fast PR feedback (PR Tests)
2. Comprehensive platform coverage (Full Tests)
3. Build and release validation (Build and Release)

ci: reorganize GitHub workflows for clear purpose and optimized coverage

---

poetry.lock
pyproject.toml
tests/test_tracing.py

add `langchain-nvidia-ai-endpoints` package as extra dep and update `langchain-community` version range.

chore(deps): add nvaie and update lc community package range

---

nemoguardrails/library/llama_guard/requirements.txt

This is in response to the dependabot security risk: (security risk https://github.com/NVIDIA/NeMo-Guardrails/security/dependabot/84).
The [dependabot84](https://github.com/NVIDIA/NeMo-Guardrails/security/dependabot/84) risk applies to vllm <= 0.8.1, this PR bumps vllm in the Llama Guard requirements.txt to 0.8.3, which I validated with a local test.
1. `python -m venv ~/env/vllm` : Create a new virtual environment.
2. `source ~/env/vllm/bin/activate`: Activate the environment.
3. `pip install -r requirements.txt` : Download the requirements file which includes vllm 0.8.3, and i
nstall them.
4. [In one terminal] `python -m vllm.entrypoints.openai.api_server --port 5123 --model meta-llama/Llama-Guard-3-1B |& tee vllm.log`: Run the vllm server with a Llama Guard 3 1B model. 
5. [In another …

Upgrade Llamaguard vllm to 0.8.3 

---

nemoguardrails/cli/__init__.py
nemoguardrails/cli/providers.py
nemoguardrails/llm/providers/__init__.py
nemoguardrails/llm/providers/providers.py
tests/test_provider_selection.py

Easily search providers and add it to your config using:
```bash
nemoguardrails find-providers
```
https://github.com/user-attachments/assets/78cd77a0-4d6a-48ac-8fcc-ef91a9b4cb2f
#1085 
#Resolves:
https://github.com/NVIDIA/NeMo-Guardrails/issues/520
#1089

feat(cli): add fuzzy find provider capability to cli

---

tests/test_streaming_handler.py

This PR prevents `RuntimeError: Event loop is closed` and `Task was destroyed but it is pending!` warnings by ensuring background tasks are correctly cancelled and awaited upon test completion.
- modified the `StreamingConsumer` class in to store its asyncio task
- added a `cancel()` method, and handle `asyncio.CancelledError`
- Updating test functions (`test_single_chunk`, `test_sequence_of_chunks`) and the helper function (`_test_pattern_case`) to call `consumer.cancel()` in a `finally` block.
Verify:
Before this PR:
```sh
poetry run pytest tests/test_streaming_handler.py
```
Notice the warnings all over the place.
after this PR:
```sh
poetry run pytest tests/test_streaming_handler.py
```
No warnings

fix(tests): ensure proper asyncio task cleanup in test_streaming_handler.py

---

docs/user-guides/guardrails-library.md

Got It AI went offline, so remove the dangling link from the navigation.

chore: Remove Got It AI from 3rd party

---

docs/user-guides/advanced/nemoguard-jailbreakdetect-deployment.md

Update docs for new configuration to use jailbreakdetect NIM.

Update docs to use `nim_base_url` per new configuration.

---

.github/dependabot.yml

didn't find it useful (might revert in future)

ci(dependabot): disable dependabot

---

nemoguardrails/library/llama_guard/requirements.txt
nemoguardrails/library/patronusai/requirements.txt

bump vllm==0.9.0
resolves https://github.com/NVIDIA/NeMo-Guardrails/security/dependabot/100
Bumps [vllm](https://github.com/vllm-project/vllm) from 0.8.5 to 0.9.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/vllm-project/vllm/releases">vllm's releases</a>.</em></p>
<blockquote>
<h2>v0.9.0</h2>
<h2>Highlights</h2>
<p>This release features 649 commits, from 215 contributors (82 new contributors!)</p>
<ul>
<li>vLLM has upgraded to PyTorch 2.7!  (<a href="https://redirect.github.com/vllm-project/vllm/issues/16859">#16859</a>) This is a breaking change for environment dependency.
<ul>
<li>The default wheel has been upgraded from CUDA 12.4 to CUDA 12.8. We will distribute CUDA 12.6 wheel on GitHub artifact.</li>
<li>As a general rule of thumb, our …

chore(deps): bump vllm to 0.9.0 in library requirements

---

nemoguardrails/rails/llm/llmrails.py
nemoguardrails/rails/llm/utils.py
tests/test_llmrails.py
tests/test_llmrails_reasoning.py
tests/test_rails_llm_utils.py

This pull request refactors and improves the handling of action details extraction from flow IDs in the LLM Rails codebase. The main change is moving the `get_action_details_from_flow_id` function from a private method in `llmrails.py` to a public utility in `utils.py`, making it more reusable and better tested. The related tests have been updated and expanded, and redundant or outdated test code has been cleaned up.
Key changes include:
**Refactoring and Code Organization:**
- Moved the `_get_action_details_from_flow_id` function from `llmrails.py` to `utils.py`, renamed it to `get_action_details_from_flow_id`, and updated all internal references to use the new import. This improves code organization and reusability. [[1]](diffhunk://#diff-d58ae43ca64fe48b2b1a1767ee9e11b277c792a936f9aaf95 …

refactor(llmrails): move get_action_details_from_flow_id to utils

---

docs/getting-started/8-tracing/1_tracing_quickstart.ipynb
docs/user-guides/tracing/adapter-configurations.md
docs/user-guides/tracing/index.md

Doc edit for the new tracing notebook

docs: doc edits for tracing notebook

---

docs/getting-started/8-tracing/1_tracing_quickstart.ipynb
docs/getting-started/8-tracing/2_tracing_with_jaeger.ipynb
docs/user-guides/tracing/adapter-configurations.md
docs/user-guides/tracing/index.md

- Edit the new tracing notebook 2, and match some styles with notebook 1. 
- Add the notebook links to the toolkit user guide.

docs: edits for tracing notebook 2

---

poetry.lock

chore(deps): update poetry.lock

---

docs/index.md
docs/user-guides/advanced/index.rst

docs: add the new page to the right index file

---

docs/user-guides/langchain/langgraph-integration.md

docs: make some doc edits

---

.github/workflows/docs-build.yaml

Chore: Update docs CI to use new repository owner so that the store-html job runs on merges to the default branch.

chore(docs): Update repository owner

---

docs/user-guides/langchain/runnable-rails.md

minor doc edits
