nemoguardrails/actions/llm/generation.py
nemoguardrails/kb/basic.py
nemoguardrails/kb/kb.py
nemoguardrails/rails/llm/config.py

1. fix 'utf-8' encoding issue for *.co and *.yml: to better support examples using prompts with different languages
2. configure embedding model through config.yaml, such that we could use multilingual embedding model

fix utf-8 encoding issue, add embedding_model configuration

---

nemoguardrails/actions/llm/generation.py

The following two lines occasionally crash the program:
```py
user_intent = get_first_nonempty_line(result)
log.info("Canonical form for user intent: " + user_intent)
```
because `user_intent` may be  equal to `None`. This is also seemingly expected as the very next line of code checks for it.
```py
if user_intent is None:
...
```
Thus it should make sense to alter the logging line to prevent the program from crashing, as follows:
```py
log.info("Canonical form for user intent: " + (user_intent if user_intent else "None"))
```

BUG: Avoid str concat with None when logging user_intent

---

examples/llm/hf_pipeline_dolly/config.py

When running guardrails with the example configuration found in `examples/llm/hf_pipeline_dolly`, the following error will occur if the host machine does not have any CUDA-enabled GPUs:
```
│ /Users/username/anaconda3/lib/python3.10/site-packages/langchain/llms/huggingface_pipeline.py:106   │
│ in from_model_id                                                                                 │
│                                                                                                  │
│   103 │   │   │                                                                                  │
│   104 │   │   │   cuda_device_count = torch.cuda.device_count()                                  │
│   105 │   │   │   if device < -1 or (device >= cuda_device_count):                               │ …
```

Fix bug in example causing config.py to crash on computers with no CUDA-enabled GPUs

---

nemoguardrails/logging/callbacks.py

See relevant LangChain Pull Request:
https://github.com/hwchase17/langchain/pull/6858
Was getting the following error:
Fixed by by providing `tags = []` and `inheritable_tags = []` arguments in callbacks.py, giving:
```
logging_callback_manager_for_chain = AsyncCallbackManagerForChainRun(
run_id=uuid.uuid4(),
parent_run_id=None,
handlers=handlers,
inheritable_handlers=handlers,
tags=[],
inheritable_tags=[],
)
```

Bug fix for callbacks

---

nemoguardrails/actions/llm/generation.py
nemoguardrails/kb/basic.py
nemoguardrails/kb/index.py
nemoguardrails/kb/kb.py
nemoguardrails/llm/providers.py
nemoguardrails/rails/llm/llmrails.py

Addressing #99. Added ability to choose embedding model via the config.yaml. Also added OpenAI API as option (alongside Sentence Transformers). We can do:
```yaml
models:
- type: main
engine: openai
model: text-davinci-003
- type: embedding
engine: openai
model: text-embedding-ada-002
```
and
```yaml
models:
- type: main
engine: openai
model: text-davinci-003
- type: embedding
engine: SentenceTransformers
model: all-MiniLM-L6-v2
```
I understand there is also some work ongoing in this space, but in a private repo, naturally, I can't see this, so I apologize if any of this conflicts with or overlaps. Let me know if any of this can be of use!
Thanks

added alternative embedding models for sentence transformers and openai

---

nemoguardrails/llm/providers.py

Fixes the following error:
```
File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/nemoguardrails/llm/providers.py:55, in discover_langchain_providers()
52 for provider_cls in _providers.values():
53     # If the "_acall" method is not defined, we add it.
54     if issubclass(provider_cls, LLM) and "_acall" not in provider_cls.__dict__:
---> 55         log.debug("Adding async support to", provider_cls.__name__)
56         provider_cls._acall = _acall
File ~/anaconda3/envs/pytorch_p310/lib/python3.10/logging/__init__.py:1465, in Logger.debug(self, msg, *args, **kwargs)
1456 """
1457 Log 'msg % args' with severity 'DEBUG'.
1458 
(...)
1462 logger.debug("Houston, we have a %s", "thorny problem", exc_info=1)
1463 """
1464 if self.isEnabledFor(DEBUG):
-> 1465     self._log(DEBUG, …
```

Fixed TypeError in logging call

---

CHANGELOG.md
nemoguardrails/rails/llm/llmrails.py

- Address verbose output issue when running Rails command from a Python script.
- When user runs rails with `verbose=true` the `set_verbose()` function is now called.
- Response to GitHub discussion #178.

Fix verbose behavior in Rails within Python script (GH-178)

---

nemoguardrails/llm/providers/providers.py

Azure support is added.
In config.xml, you could configure 'azure' as provider, like:
models:
- type: main
engine: azure
model: gpt-4-1106-preview
parameters:
azure_endpoint: <the end point of the deployment>
api_version: 2023-07-01-preview
deployment_name: <your deployment name>
api_key: <your azure key>

azure is supported

---

examples/notebooks/generate_events_and_streaming.ipynb

This PR adds an example of streaming the bot response when using the events-based API.

Add example of using `generate_events_async` with streaming.

---

docs/user_guides/advanced/llama-guard-deployment.md

Asserted that no other occurrences of `0.0.0.0` exist in other documentation. The only other occurrences are in the `uvicorn.run` commands in the [CLI app](https://github.com/search?q=repo%3ANVIDIA%2FNeMo-Guardrails%20uvicorn.run&type=code).

Update llama guard deployment docs

---

examples/configs/guardrails_only/README.md
examples/configs/guardrails_only/demo.py
examples/configs/guardrails_only/input/config.co
examples/configs/guardrails_only/input/config.yml
examples/configs/guardrails_only/output/config.co
examples/configs/guardrails_only/output/config.yml

This PR includes an example of how to invoke only the input/output rails in a configuration without invoking the generation.

Add example configurations for using only the guardrails, without LLM generation.

---

nemoguardrails/embeddings/basic.py
tests/test_batch_embeddings.py
tests/test_perf_1.py

WIP: enable batching when computing the embeddings. Initial tests show a 3x throughput increase. To be tested some more.

Make embeddings computing async and add support for batching.

---

CHANGELOG.md
nemoguardrails/rails/llm/config.py

Fixed #285 - using the same evaluation set given a random seed for topical rails

Fixed #285 - using the same evaluation set given a random seed for topical rails

---

nemoguardrails/actions/retrieve_relevant_chunks.py

The retrieval method presently does not log the individual retrieved chunks (only a concatenation) and does not indicate whether the chunks were due to the most recent user question or retrieved as part of some earlier call. This PR adds two things to the context updates:
- `relevant_chunks_sep: List[str]`, a list of the individual chunks retrieved, and
- `retrieved_for: Optional[str]`, the user message for which the chunks were retrieved only if the returned chunks were for a user message. If they were from an earlier call, this will None.

add more information to results of `retrieve_relevant_chunks`

---

docs/user_guides/guardrails-library.md
examples/configs/rag/custom_rag_output_rails/README.md
examples/configs/rag/custom_rag_output_rails/config.py
examples/configs/rag/custom_rag_output_rails/config.yml
examples/configs/rag/custom_rag_output_rails/kb/report.md
examples/configs/rag/custom_rag_output_rails/rails/output.co

Hi @drazvan,
First, thanks for NeMo Guardrails.
With this pull request, I add an example that demonstrates the use of output rails when using a custom RAG.
Please refer to the README files that come with this pull request.
Fixes #227
```shell
$ export OPENAI_API_KEY='your API key'
$ nemoguardrails chat --config <your_root>/NeMo-Guardrails/examples/configs/rag/custom_rag_output_rails --verbose
```
You may be prompted to install: `pip install langchain-openai` because this example uses it.

Update documentation to demonstrate the use of output rails when using a custom RAG

---

nemoguardrails/actions/action_dispatcher.py
nemoguardrails/actions/llm/utils.py
nemoguardrails/eval/evaluate_factcheck.py
nemoguardrails/library/hallucination/actions.py
nemoguardrails/library/llama_guard/actions.py
nemoguardrails/library/self_check/facts/actions.py
nemoguardrails/library/self_check/input_check/actions.py
nemoguardrails/library/self_check/output_check/actions.py
nemoguardrails/llm/taskmanager.py
nemoguardrails/rails/llm/config.py
tests/test_llm_task_manager.py

This is an initial start of #224 
I wanted to open this PR to make sure the maintainers were okay with the direction.
`stop` is sort of an odd parameter that doesn't have an obvious place to live (from what I saw...very well could be wrong).
Thanks!

Adds configurable stop tokens

---

nemoguardrails/actions/llm/generation.py
nemoguardrails/colang/v2_x/runtime/statemachine.py
nemoguardrails/rails/llm/llmrails.py
tests/test_nest_asyncio.py

Other components might cache it, like `openai` and it would break things.

Fix #320. Reuse the asyncio loop between sync calls 

---

nemoguardrails/embeddings/embedding_providers/fastembed.py
nemoguardrails/library/jailbreak_detection/Dockerfile
nemoguardrails/library/jailbreak_detection/Dockerfile-GPU
nemoguardrails/library/jailbreak_detection/actions.py

Fix a few issues related to jailbreak detection heuristics. 

---

nemoguardrails/actions/v2_x/generation.py
nemoguardrails/colang/runtime.py
nemoguardrails/colang/v2_x/lang/colang_ast.py
nemoguardrails/colang/v2_x/lang/grammar/colang.lark
nemoguardrails/colang/v2_x/lang/parser.py
nemoguardrails/colang/v2_x/lang/transformer.py
nemoguardrails/colang/v2_x/library/core.co
nemoguardrails/colang/v2_x/library/utils.co
nemoguardrails/colang/v2_x/runtime/flows.py
nemoguardrails/colang/v2_x/runtime/runtime.py
nemoguardrails/colang/v2_x/runtime/statemachine.py
nemoguardrails/rails/llm/config.py
nemoguardrails/rails/llm/llmrails.py
tests/colang/parser/v2_x/inputs/test11.co
tests/colang/parser/v2_x/inputs/test12.co
tests/colang/parser/v2_x/inputs/test13.co
tests/colang/parser/v2_x/test_ast.py
tests/colang/parser/v2_x/test_basic.py
tests/colang/parser/v2_x/test_syntax_parsing.py
tests/test_configs/with_custom_action_v2_x/config.co
tests/test_configs/with_imports_1/config.yml
tests/test_configs/with_imports_1/main.co
tests/v2_x/test_decorator_parsing.py
tests/v2_x/test_expr_statement.py
tests/v2_x/test_flow_params.py
tests/v2_x/test_imports.py
tests/v2_x/test_run_actions.py

- allow operators and keywords to be part of flow names
- allow any function to be used in expressions
- add support for decorators
- add support for `import` statement
- add support for expression statements, e.g., `($a.append('b'))`

Colang parser improvements

---

nemoguardrails/colang/v2_x/runtime/eval.py
tests/v2_x/test_slide_mechanics.py

Fix updating dictionary variables in Colang 2

Fix dictionary expression evaluation bug

---

nemoguardrails/eval/evaluate_factcheck.py
nemoguardrails/eval/evaluate_moderation.py
nemoguardrails/llm/taskmanager.py

Evaluate was not working with chat LLMs from Langchain for factchecking and moderation. Added support for this. 
Fixes #420

Fix #420 - evaluate not working with chat models

---

nemoguardrails/server/api.py

This PR addresses a directory traversal bug in the config file loading process and enhances path security. It resolves #481.
- **Bug Fix**: Resolved an issue where relative paths led to incorrect directory traversal during config file loading.

Fix directory traversal bug

---

nemoguardrails/llm/params.py
tests/test_llm_params.py

This PR addresses the bug in the `LLMParams` class. The bug was causing incorrect handling of parameters that were not directly attributes of the `llm` object but were present in the `model_kwargs` dictionary. It resolves #158.
The changes ensure that if a parameter is not an attribute of `llm`, it checks if `llm` has an attribute `model_kwargs`. If `model_kwargs` exists, it checks if the parameter is in `model_kwargs`. If it is, it saves the original value and sets the new value. If it's not, it logs a warning and sets the new value. 
Upon exiting the context manager, the original parameters are restored correctly, whether they were direct attributes of `llm` or keys in `model_kwargs`.
In addition to the bug fix, this PR also enhances the unit tests to cover these cases.

Fix LLMParams bug and add unit tests (fixes #158)

---

docs/user_guides/configuration-guide.md

Provides an example for using open-source LLMs with [Ollama](https://ollama.com/).

docs: add example config for using models with ollama

---

nemoguardrails/llm/prompts.py

Fixed an issue where the LLM model and custom prompts could not distinguish between main and other tasks.

Fix select model type and custom prompts task.py

---

docs/user_guides/configuration-guide.md

If you make custom prompt work as per #486, you should write the output parser. 
Additionally, it seems that need to list all the items available as config for prompts in this user guide file.

Fix custom prompts configuration manual.md

---

nemoguardrails/actions/actions.py

`action` decorator does not preserve the decorator argument options if applied to staticmethods or classmethods. For example:
```python
import os
from nemoguardrails import LLMRails
from nemoguardrails import RailsConfig
from nemoguardrails.actions.actions import action
os.environ["OPENAI_API_KEY"]="sk-..."
config = RailsConfig.from_path(".")
rails = LLMRails(config)
@action(name="func")
def test_func():
return "hello"
class Test:
@action(name="method")
def test_method(self):
return "method"
@action(name="staticmethod")
@staticmethod
def test_staticmethod():
return "static"
@action(name="classmethod")
@classmethod
def test_classmethod(cls):
return "class"
rails.register_action(test_func)
rails.register_action(Test().test_method)
rails.register_action(Test.test_staticmethod) …
```

[bugfix] staticmethod and classmethod action decorators fix

---

Dockerfile
nemoguardrails/library/factchecking/align_score/Dockerfile
nemoguardrails/library/jailbreak_detection/Dockerfile
nemoguardrails/library/jailbreak_detection/Dockerfile-GPU

Hi, thanks for developing the guardrails.
Removing the pip cache in a layer subsequent to the pip install does not reduce image size because the cache stays in the final image. It is more effective and cleaner not using any caching at all.
Adding the option `--no-cache-dir` during pip command reduces the final artifact size for each of the Dockerfiles in the repo, like listed below.
1. `Dockerfile`: from 1.68GB to 1.58GB;
2. `nemoguardrails/library/jailbreak_detection/Dockerfile`: from 12.3GB to 9.37GB;
3. `nemoguardrails/library/jailbreak_detection/Dockerfile-GPU`: from 12.3GB to 9.41GB;
4. `nemoguardrails/library/factchecking/align_score/Dockerfile`: from 9.6GB to 7.6GB;
For the last three dockerfiles, I reordered the COPY and RUN directives in order to avoid having to download the …

Do not store pip cache during docker build

---

nemoguardrails/cli/__init__.py
nemoguardrails/server/api.py

This PR includes three key fixes:
1. Prevents path traversal in the `_get_rails` function by rejecting config_ids that contain dangerous characters or sequences.
2. Removes an unnecessary path check in the `_get_rails` function, simplifies the code and reducing the chance of errors.
3. Modifies the server command in the CLI to correctly expand user paths, allowing for paths starting with '~' to be used.
fixes [4706127]

Fix path traversal check

---

examples/configs/llm/llama-3/config.yml
nemoguardrails/actions/llm/generation.py
nemoguardrails/actions/llm/utils.py
nemoguardrails/llm/filters.py
nemoguardrails/llm/prompts.py
nemoguardrails/llm/prompts/llama3.yml
nemoguardrails/llm/taskmanager.py
nemoguardrails/logging/callbacks.py
nemoguardrails/logging/verbose.py
tests/test_llm_task_manager.py

A set of improvements to the prompts for Llama-3 and Llama-3.1 models.

Prompt improvements Llama-3

---

nemoguardrails/llm/prompts/openai-gpt35-instruct.yml
nemoguardrails/llm/prompts/openai.yml
tests/test_llm_task_manager.py

The change in default prompts coupled with the partial name matching for task templates (added as part of Llama-3 prompts improvements) resulted in `gpt-3.5-turbo-instruct` using the prompts for `gpt-3.5-turbo` (which are chat templates, and not working great). This PR adds back the original prompts explicitly for `gpt-3.5-turbo-instruct`.

Fix gpt-3.5-turbo-instruct prompt.

---

docs/user_guides/guardrails-library.md
examples/configs/rag/custom_rag_output_rails/config.yml
examples/sample_config.yml
nemoguardrails/eval/evaluate_hallucination.py
nemoguardrails/library/hallucination/actions.py
nemoguardrails/library/hallucination/flows.co
nemoguardrails/llm/filters.py
nemoguardrails/llm/prompts/nemollm.yml
nemoguardrails/llm/types.py
tests/test_configs/with_prompt_modes/prompts/prompts.yml
tests/test_prompt_modes.py

This PR renames all instances of 'check_hallucination' to 'self_check_hallucination' across multiple files. This includes changes in function names, task names, and documentation. It resolves #664.
Also it is mentioned in #589 
-[ ] Fix #182 afer discussion

Fix: hallucination-check 

---

nemoguardrails/llm/prompts/openai.yml

The `relevant_chunks` were missing from the general prompt for `gpt-3.5-turbo-instruct` model.

Add the `relevant_chunks` to the gpt-3.5 general prompt template.

---

docs/user_guides/advanced/embedding-search-providers.md
docs/user_guides/configuration-guide.md
nemoguardrails/actions/llm/generation.py
nemoguardrails/embeddings/basic.py
nemoguardrails/embeddings/index.py
nemoguardrails/logging/verbose.py
nemoguardrails/rails/llm/config.py
nemoguardrails/rails/llm/llmrails.py
tests/test_embeddings_only_user_messages.py

This commit introduces a search threshold to the `BasicEmbeddingsIndex` class. This threshold is used to filter the search results based on their distances. The `_filter_results` method is added to perform this filtering. The `search` method is updated to use this new feature. The `search_threshold` parameter is also added to the `LLMRails` classs.
TODO:

feat(embeddings): add search threshold to BasicEmbeddingsIndex

---

nemoguardrails/actions/llm/generation.py
nemoguardrails/rails/llm/llmrails.py

The changes include the addition of `__getstate__` and `__setstate__` and methods to the `LLMRails` class. These methods are used for pickling and unpickling of the class instance, allowing it to be serialized and deserialized.
It might resolve #614

feat(llmrails): Add serialization support for LLMRails

---

nemoguardrails/eval/ui/common.py
nemoguardrails/eval/ui/pages/0_Config.py
nemoguardrails/eval/ui/pages/1_Review.py
nemoguardrails/eval/ui/streamlit_utils.py
nemoguardrails/eval/ui/utils.py

Move `get_span_colors` and `load_eval_data` to `streamlit_utils`.

fix:  streamlit import error

---

nemoguardrails/integrations/langchain/runnable_rails.py
nemoguardrails/integrations/langchain/utils.py
tests/test_runnable_rails.py

fix: updated the code to pass config and kwargs to passthrough_fn
also wrapped synchronous runnable into asynchronous so that it stays consistent with all synchronous runnables
[issue link](https://github.com/NVIDIA/NeMo-Guardrails/issues/665)

Fix: pass config and kwargs to passthrough_fn runnable for issue 665

---

nemoguardrails/cli/migration.py

This PR replaces hyphens and apostrophes in lines that start with 'bot' or 'user', migrating the abc bot was raising parsing error as the most recent change to this file limited this substitution to the flow definition line.

fix(migration): replace hyphens and apostrophes

---

nemoguardrails/colang/v2_x/runtime/runtime.py
tests/v2_x/test_outgoing_events.py

Fixes a bug in the Colang 2 runtime, that causes certain output events to be not fed as input events again. This happens if multiple input_events are processed at the same time and all of these events generate output_events.
This PL fixes this by maintaining a separate list of output events that need to be added to the input event list to continue processing.

Fix: Process all outgoing events

---

docs/colang_2/language_reference/the-standard-library.rst
nemoguardrails/colang/v2_x/library/avatars.co

The two flows `scene show choice` and `scene show form` are currently not functional.  This PL provides a minimal functional implementation. More can be done in the future to make the flows more flexible.

Fix the scene form and choice flows in the Colang 2 standard library

---

nemoguardrails/llm/prompts/llama3.yml
nemoguardrails/llm/prompts/openai-chatgpt.yml
nemoguardrails/llm/prompts/openai.yml

Add relevant chunks for `generate_flow_continuation` and `generate_user_intent_and_bot_action_from_user_action` tasks
tested with abc_v2 config (also for meta/llama3-70b-instruct) without kb folder.
```python
from nemoguardrails import LLMRails, RailsConfig
config = RailsConfig.from_path("./examples/bots/abc_v2")
rails = LLMRails(config)
response = rails.generate(messages=[{
"role": "context",
"content": {
"relevant_chunks": """
Employees are eligible for the following time off:
* Vacation: 15 days per year, accrued monthly.
* Sick leave: 25 days per year, accrued monthly.
* Personal days: 5 days per year, accrued monthly.
* Paid holidays: New Year's Day, Memorial Day, Independence Day, Thanksgiving Day, Christmas Day.
* Bereavement leave: 3 days paid leave for immediate family members, 1 …
```

feat: add relevant chunks prompts 

---

nemoguardrails/rails/llm/default_config_v2.yml

This PR adds one more demonstration to the sample conversation default prompts of v2 for multiline text output with `bot say` flow. Before this PR, any dynamic code generation with LLMs that needed more than one line resulted in syntax error.
Example Colang application:
```colang
import core
import llm
flow main
activate llm continuation
```
Example application trace:
```bash
> Give a list of car manufacturers                                                                                                                                                                          
⠙ Working ...WARNING:nemoguardrails.colang.v2_x.runtime.runtime:Failed parsing a generated flow
@meta(bot_intent="bot respond provide a list of car manufacturers")
flow _dynamic_e8e6537a bot respond provide a list …
```

Fix multiline LLM output syntax error for dynamic flow generation

---

pyproject.toml

Because of known vulnerabilities, Jinja2 and Langchain have been upgraded.
- The current version of the Langchain package contains several critical and high vulnerabilities. It must be upgraded to at least version 0.2.14.
- The current Jinja2 version exposes a high-severity vulnerability that is fixed in version 3.1.4.

chore: Upgrade langchain-core and jinja

---

nemoguardrails/llm/prompts/llama3.yml
nemoguardrails/llm/prompts/openai-chatgpt.yml
tests/v2_x/test_state_serialization.py

* Fixes the assigned prompt role.
* Also increases a unit test threshold since it sporadically still fails.

Fix/colang 2/flow continuation prompt

---

nemoguardrails/colang/v2_x/library/llm.co

We need to remove it since otherwise it will be prompted as potential user intent in all intent derivations when llm module is included that leads to unexpected behaviours.

Remove the user intent from llm library module

---

nemoguardrails/colang/v2_x/runtime/statemachine.py

With the introduction of $self we no longer need this restriction for variable names.

Remove deprecated warning

---

examples/configs/rag/custom_rag_output_rails/config.py
examples/configs/rag/multi_kb/config.py
examples/configs/rag/pinecone/config.py
examples/scripts/demo_llama_index_guardrails.py
nemoguardrails/actions/llm/generation.py
nemoguardrails/actions/v2_x/generation.py
nemoguardrails/library/content_safety/actions.py
nemoguardrails/library/factchecking/align_score/actions.py
nemoguardrails/library/hallucination/actions.py
nemoguardrails/library/llama_guard/actions.py
nemoguardrails/library/patronusai/actions.py
nemoguardrails/library/self_check/facts/actions.py
nemoguardrails/library/self_check/input_check/actions.py
nemoguardrails/library/self_check/output_check/actions.py
nemoguardrails/llm/helpers.py
nemoguardrails/llm/providers/_langchain_nvidia_ai_endpoints_patch.py
nemoguardrails/llm/providers/nemollm.py
nemoguardrails/llm/providers/providers.py
nemoguardrails/llm/providers/trtllm/llm.py
nemoguardrails/rails/llm/llmrails.py
pyproject.toml
tests/test_configs/with_custom_llm_prompt_action_v2_x/actions.py
tests/utils.py

This pull request makes the necessary changes to upgrade LangChain to version 0.3. 
1. **Update Pydantic Import Paths**:
- Update import paths for `pydantic.v1` to ensure compatibility with the latest version of Pydantic.
- Suppress specific warnings related to protected namespaces in Pydantic models by adding filter to ignore them. 
2. **Update LangChain Version Constraints**:
- Update version constraints for `langchain`, `langchain-core`, and `langchain-community` to allow versions up to <0.4.0.
3. **Refactor Import Paths for BaseLLM**:
- Update import paths for `BaseLLM` to `langchain_core.language_models.llms` across multiple files to align with the latest version of LangChain.

Feat: Upgrade LangChain to Version 0.3

---

CONTRIBUTING.md

Added correct python command version
Added correct python command version. Latest version of python works with `python3` instead on `python`
NA

Doc: Added correct python command version

---

CONTRIBUTING.md

This PR contains a very small documentation change in the `CONTRIBUTING.md` file. The folder name in the command after cloning the repository was incorrect and facing error with pre-commit setup, and I have fixed it to reflect the correct name and command.
While running this:
```
python -m pre-commit install
```
/Users/.../OSS/NeMo-Guardrails/venv/bin/python: No module named pre-commit

Doc: Fix incorrect folder name & pre-commit setup in CONTRIBUTING.md

---

.github/workflows/build-wheel.yml
CONTRIBUTING.md
README.md
docs/getting_started/installation-guide.md
pyproject.toml

Dropping Python 3.8 support as it has reached its EOL on 2024-10-07 (https://peps.python.org/pep-0569/)

chore: drop support for Python 3.8

---

nemoguardrails/rails/llm/config.py
nemoguardrails/utils.py
tests/test_configs/railsignore_config/config_to_load.co
tests/test_configs/railsignore_config/ignored_config.co
tests/test_railsignore.py

PR adding support for a .railsignore to ignore .co files in LLMRails / RailsConfig.
For issue: https://github.com/NVIDIA/NeMo-Guardrails/issues/277
Tests added and passing fully.
Two follow ups after this PR are:
1. Looking into add ignoring .py files for ActionDispatcher
2. Discuss if we want .kb files to be specified as a follow up.

feat: railsignore added for config loading of LLMRails / RailsConfig.

---

nemoguardrails/llm/prompts/openai.yml

Otherwise the bot will generate based on the relevant chunks only.

fix: move relevant chunks before current conversations

---

nemoguardrails/actions/v2_x/generation.py
nemoguardrails/colang/v2_x/library/passthrough.co
tests/v2_x/test_passthroug_mode.py

To enable passthrough mode in Colang 2.x one needs to import passthrough module and activate llm continuation in the main flow.
```co
import passthrough
flow main
activate llm continuation
...
```

Feat: support passthrough mode in colang 2

---

docs/colang_2/language_reference/development-and-debugging.rst
nemoguardrails/cli/debugger.py

This improves the visualization of the CLI `!tree` command to include parent flow instances and dim flow instances that are no longer active.

Add parent instances of restarted activated flow instances

---

nemoguardrails/library/cleanlab/actions.py

Cleanlab's latest release (v2.5 on 09/20) to `cleanlab-studio` pypi package updates the return type of `get_trustworthiness_score_async()` method from `float` to `typeddict`. Therefore, the `trustworthiness_score` is indexed out from the typed dict.
The fix is verified after updating `pip install -U cleanlab-studio`.

fix(library): Update Cleanlab's return type

---

nemoguardrails/colang/v2_x/lang/grammar/colang.lark

This PR fixes a problem related to parsing nested if/else in Colang 2. The problem is that whenever there is an `if` inside an `else`, the parser considers that as an `elif` node. However, this could be problematic, as the `if` might not meant to be an `elif` to the outer `if`. Consider the following examples:
```colang
flow main
$t = 1
if $t == 1
print "t is 1"
else
if $t == 1
print "t is really 1"
else
print "t may not be 1"
```
This example results in parsing error. This is because the `else` statement of the outer `if`, is combined with the `if` after that and is considered as `elif`. Therefore, the last `else` statement is not parseable, because there is no `if` related to that anymore! If you add anything between `else` and the `if`, even an optional `:` or a comment, it will fix …

Fix else if parsing problem

---

nemoguardrails/library/factchecking/align_score/Dockerfile

Fixes an issue where `alignscore-server` (defined in [nemoguardrails/library/factchecking/align_score/Dockerfile](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/library/factchecking/align_score/Dockerfile)) throws a runtime `LookupError(resource_not_found)` error. This error seems to be due to a [breaking change in `nltk`](https://github.com/nltk/nltk/issues/3293). Please see steps below to reproduce.
cc: @drazvan 
Build `alignscore-server` Docker Image:
```sh
cd nemoguardrails/library/factchecking/align_score
docker build -t alignscore-server .
```
Run `alignscore-server`:
```sh
docker run -p 5123:5000 alignscore-server
```
Send a request to `alignscore-server` (executed from a local notebook):
```python
from nemoguardrails.library.factchecking.align_score.request …
```

Download nltk's punkt_tab in align_score Dockerfile

---

Dockerfile
pyproject.toml

Setuptools is unable to resolve the dependency graph when eval is included  in the all dependencies list. This issue is primarily caused by a limitation of pip and a conflict with streamlit. Removing eval from the all dependencies list resolves this issue. Eval can be installed separately if needed.

fix(pyproject.toml): remove eval from all dependencies

---

.vscode/settings.json
docs/colang_2/examples/test_csl.py
docs/colang_2/examples/utils.py
nemoguardrails/cli/chat.py
nemoguardrails/colang/v2_x/library/core.co
pytest.ini
tests/utils.py
tests/v2_x/chat.py

This PR introduces necessary additions to the testing framework to allow for automated testing of Colang example snippets in the Colang 2 documentation. As an intial use case for this this PR also contains a reworked standard library documentation that adds concrete examples to most flows in `core.co`, `timing.co`, and `llm.co`.
Additional changes:
- Fix in `core.co` for the `bot started saying $text` and `bot said $text` flows
- Generate `UtteranceUserActionStarted` events in chat CLI
- Add Colang Doc tests to pytest.ini such that they are run in CI

Automated Colang Standard Library (CSL) documentation tests

---

docs/getting_started/installation-guide.md
pyproject.toml

Explicitly pinning the version of pandas to avoid pip resolution issues. This ensures compatibility with streamlit, which requires pandas>=1.4.0,<3.
For v0.10.0 and v0.10.1, and the head of the develop branch prior to commit d69a7e882cc66bfe8fe9b9728d9c0b367211beb5, pip fails to resolve dependencies. This issue is due to a problem with pip's dependency resolution.
For v0.10.0 and v0.10.1, and the head of the develop branch prior to commit d69a7e882cc66bfe8fe9b9728d9c0b367211beb5, pip fails to resolve dependencies. This issue is due to a problem with pip's dependency resolution. 
```sh
pip install "nemoguardrails[all]"
```
To avoid these conflicts, we recommend using a `constraints.txt` file to specify the exact version of `pandas`.
**Example `constraints.txt`**:
```
pandas>=1.4.0,<3
``` …

fix(dependencies): add pandas version constraint for eval

---

docs/getting_started/installation-guide.md

include easier to follow installation note in the documentation as it’s easier for the user (vs. creating a separate file).

docs(installation): update optional dependencies install

---

docs/user_guides/advanced/generation-options.md
docs/user_guides/server-guide.md

Updated the role from "bot" to "assistant" in the documentation to avoid incorrect behavior of the codebase. This change affects the advanced generation options guide and the server guide.
Changes:
- Updated role in `generation-options.md` examples.
- Updated role in `server-guide.md` examples.
#827

docs: update role from bot to assistant

---

nemoguardrails/actions/llm/generation.py

Updated the condition to check if `prompt_config.output_parser` is in the list `["verbose_v1", "bot_message"]`
Currently this part of code needs to be updated once new output_parsers get registered.
#850

fix: handle multiple output parsers in generation

---

tests/conftest.py

The tests in `tests/test_cli.py` and `tests/test_cli_migration.py` were failing with the following error:
```
prompt_toolkit.output.win32.NoConsoleScreenBufferError: Found xterm-256color, while expecting a Windows console. Maybe try to run this program using "winpty" or run it in cmd.exe instead. Or otherwise, in case of Cygwin, use the Python executable that is compiled for Cygwin.
```
This error occurs because the `prompt_toolkit` library expects a Windows console but find `xterm-256color` instead. This happens when running tests in an environment that doesn't have a proper console buffer. This issue occurs in Windows GitHub runners when the runner is `windows-latest`.
The `PromptSession` class from the `prompt_toolkit` library attempts to create a console application, which fails in …

fix(tests): mock PromptSession to prevent console error

---

docs/user_guides/community/gotitai.md
docs/user_guides/guardrails-library.md

Issues a deprecation notice for the Got It AI integration. Got It AI's RAG Truthchecking service will be discontinued on 15th December, 2024.
Changes:
- Issued deprecation notice in gotitai.md
- Issued deprecation notice in guardrails-library.md
@cparisien @drazvan

docs: add deprecation notice for Got It AI integration

---

nemoguardrails/cli/chat.py

This fixes an asyncio loop issue in the chat CLI with Python 3.8.

Fix asyncio loop issue in combination with enable_input event

---

examples/configs/content_safety/prompts.yml

This PR contains a very small change in the example prompts, where a few typos are fixed in order to get rid of some of the IDE warnings.
Hi @Pouyanpi, thank you for the comments on [PR-808](https://github.com/NVIDIA/NeMo-Guardrails/pull/808). This is a new PR with the same changes as in [PR-808](https://github.com/NVIDIA/NeMo-Guardrails/pull/808), incorporating your feedback.
NA

Fix typos in the example prompts to remove some of the IDE warnings

---

poetry.lock
pyproject.toml

4.1.0 instroduces rust-pystemmer which does not have any license

chore: pin fastembed to 4.0.0

---

.github/workflows/full-tests.yml
.github/workflows/pr-tests.yml
.github/workflows/test-and-build-wheel.yml

add missing event types for PR triggers in 
- `build-and-test-wheel` workflow to avoid running this test on push events. And on workflow changes in `.github`
- full tests on workflow changes in `.github`

fix(ci): add missing event types for PR trigger

---

nemoguardrails/library/privateai/actions.py
nemoguardrails/library/privateai/request.py

This PR aims to resolve "Incomplete URL substring sanitization" Error thrown by CodeQL.

Private AI URL Parsing Fix

---

docs/colang-2/examples/test_csl.py

Ensure that the main flow is not finishing before the two "tick" utterances are completed.

Fix repeating timer flow doc test.

---

docs/user-guides/community/active-fence.md

With the current [action](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/library/activefence/actions.py#L29) expected input, the docs are out of date.

fix activefence rail docs

---

docs/colang-2/examples/test_csl.py
docs/colang-2/language-reference/csl/core.rst
nemoguardrails/colang/v2_x/library/core.co

Adds a `wait until done` utility flow into `core.co` that waits until a flow or action is finished or stopped. This intended to be used whenever the user is interested in whether a flow or action has finished but might miss the Finished() events, e.g. as part of `when` statements.

Add utility flow `wait until done`

---

.github/workflows/full-tests.yml

It removes the dead code in full-tests workflow.
Recent Github Runner runs against out of scope test matrix.
The issue happened in #927 in full-tests job where it wrongly used Ubuntu as OS with Python 3.12.

chore: remove Ubuntu from full-tests workflow

---

README.md
docs/user-guides/community/active-fence.md
docs/user-guides/guardrails-library.md
examples/sample_config.yml
nemoguardrails/library/activefence/actions.py
nemoguardrails/library/activefence/flows.co
nemoguardrails/library/activefence/flows.v1.co
tests/test_activefence_rail.py

The current implementation of activefence action allows sending only user messages to activefence API.
This PR allows sending LLM output messages to Activefence API as part ofthe output rail.

define input and output flows explicitly

---

docs/user-guides/community/privateai.md
docs/user-guides/guardrails-library.md
examples/configs/privateai/pii_masking/config.yml
examples/notebooks/privateai_pii_detection.ipynb
nemoguardrails/library/privateai/actions.py
nemoguardrails/library/privateai/flows.co
nemoguardrails/library/privateai/flows.v1.co
nemoguardrails/library/privateai/request.py
tests/test_privateai.py

This PR enhances [Private AI](docs.private-ai.com) integration by adding support for PII masking capabilities. Previously, Private AI integration allowed for PII detection, preventing texts containing PII from being sent to the LLM or end user. With the new masking feature, texts can now be sanitized and shared with the LLM or user in a masked format.
For example, given the user input:
```
My email id is user@email.com
```
The PII masking configuration can transform the text into:
```
My email id is [EMAIL]
```
This enables safe data handling while maintaining the contextual integrity of the input.
@Pouyanpi

feat: add pii masking capability to private ai integration

---

docs/user-guides/community/presidio.md
nemoguardrails/library/sensitive_data_detection/actions.py
nemoguardrails/rails/llm/config.py
tests/test_sensitive_data_detection.py

Currently the `AnalyzerEngine` uses `default_score_threshold` of 0. This PR adds `score_threshold` to `SensitiveDataDetectionOptions` so that the user can set it in the `config.yml`. The default value is set to `0.2` but it requires further experimentation.
Example configuration:
```yaml
rails:
config:
sensitive_data_detection:
input:
score_threshold: 0.4
entities:
- PHONE_NUMBER
- EMAIL_ADDRESS
- IN_PAN
- IN_AADHAAR
output:
entities:
- PHONE_NUMBER
- EMAIL_ADDRESS
- IN_PAN
- IN_AADHAAR
```
- Fixes #818

feat: add score threshold to AnalyzerEngine

---

.github/workflows/docs-build.yaml

Add the HTML to `gh-pages` in a directory that matches the pushed ref, like `develop`.

Use ref name as dir for push build

---

docs/user-guides/advanced/nemoguard-contentsafety-deployment.md
docs/user-guides/advanced/nemoguard-topiccontrol-deployment.md

Fix use of '$oauthtoken' in sample command.
Review HTML:
* https://nvidia.github.io/NeMo-Guardrails/review/pr-957/user-guides/advanced/nemoguard-contentsafety-deployment.html#access
* https://nvidia.github.io/NeMo-Guardrails/review/pr-957/user-guides/advanced/nemoguard-topiccontrol-deployment.html#access

Typos with oauthtoken

---

nemoguardrails/library/jailbreak_detection/actions.py

`actions.py` for jailbreak models throws a `TypeError` since the `jailbreak` dictionary is already unpacked by the server.
- [ x ] I've read the [CONTRIBUTING](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/CONTRIBUTING.md) guidelines.
- [ x ] I've updated the documentation if applicable.
- [ x ] I've added tests if applicable.
- [ x ] @mentions of the person or team responsible for reviewing proposed changes.

Fix TypeError from attempting to unpack already-unpacked dictionary.

---

nemoguardrails/actions/action_dispatcher.py
tests/test_action_dispatcher.py

If `relative_to` method fails, the exception returns the `ValueError` caused by this failure instead of the actual exception. This fix ensures that the exception is handled properly.

fix: handle non-relative file paths

---

nemoguardrails/actions/actions.py
nemoguardrails/library/activefence/actions.py
nemoguardrails/library/autoalign/actions.py
nemoguardrails/library/cleanlab/actions.py
nemoguardrails/library/content_safety/actions.py
nemoguardrails/library/factchecking/align_score/actions.py
nemoguardrails/library/gcp_moderate_text/actions.py
nemoguardrails/library/hallucination/actions.py
nemoguardrails/library/jailbreak_detection/actions.py
nemoguardrails/library/llama_guard/actions.py
nemoguardrails/library/patronusai/actions.py
nemoguardrails/library/privateai/actions.py
nemoguardrails/library/prompt_security/actions.py
nemoguardrails/library/self_check/facts/actions.py
nemoguardrails/library/self_check/input_check/actions.py
nemoguardrails/library/self_check/output_check/actions.py
nemoguardrails/library/sensitive_data_detection/actions.py
nemoguardrails/library/topic_safety/actions.py
tests/test_actions.py
tests/test_actions_server.py

This PR introduces a unified mechanism for interpreting the outputs of various actions by adding dedicated mapping functions. These mapping functions determine whether an action’s response should trigger a block (e.g., refuse to respond) based on consistent thresholds and criteria.
Output mapping is essential because our actions currently return heterogeneous result types and semantics, making it challenging to consistently determine whether an action’s output should be blocked or not. 
- The `@action` decorator has been extended to accept an optional `output_mapping` parameter. This mapping is stored in the action’s metadata and is used to interpret the result of the action.
- mapping functions added to all actions in the guardrails library
- adding kwargs arg to all actions
- adding …

Feat: Unified Output Mapping for Actions

---

nemoguardrails/library/jailbreak_detection/Dockerfile
nemoguardrails/library/jailbreak_detection/Dockerfile-GPU

Jailbreak container fails to build on most systems due to hf rejecting git clone.
- [ x ] I've read the [CONTRIBUTING](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/CONTRIBUTING.md) guidelines.
- [ x ] I've updated the documentation if applicable.
- [ x ] I've added tests if applicable.
- [ x ] @mentions of the person or team responsible for reviewing proposed changes.

Fix bug with git to fetch models, use wget instead

---

.github/workflows/_test.yml
.github/workflows/latest-deps-tests.yml

This workflow allows us to identify any issues caused by the latest dependencies.
- Update dependencies to the latest version
- Install extra (optional) dependencies
- Run tests

ci: add upgrade-deps option to test workflow

---

nemoguardrails/rails/llm/llmrails.py
tests/test_llmrails.py

Allows applying output rails on any co file (previously it was limited only to v1.co files)

fix: update filename check to support any .co file

---

.vscode/settings.json

I'd like to prevent markdownlint from preventing me to include the prompt in console code blocks.

chore(docs): Tolerate prompt in code blocks

---

.vscode/settings.json

Maintain YAML files with two space indention.

YAML indent two spaces

---

poetry.lock
pyproject.toml

blis 0.1.2 has dropped Aarch64 support see https://github.com/explosion/cython-blis/issues/117

chore(deps): cap spacy to <3.8.0 due to blis issue

---

docs/getting-started/1-hello-world/config/config.yml
docs/getting-started/1-hello-world/config/rails.co
docs/getting-started/2-core-colang-concepts/config/config.yml
docs/getting-started/2-core-colang-concepts/config/rails.co
docs/getting-started/4-input-rails/config/config.yml
docs/getting-started/4-input-rails/config/prompts.yml
docs/getting-started/5-output-rails/config/actions.py
docs/getting-started/5-output-rails/config/config.yml
docs/getting-started/5-output-rails/config/prompts.yml
docs/getting-started/5-output-rails/config/rails/blocked_terms.co
docs/getting-started/6-topical-rails/config/actions.py
docs/getting-started/6-topical-rails/config/config.yml
docs/getting-started/6-topical-rails/config/prompts.yml
docs/getting-started/6-topical-rails/config/rails/blocked_terms.co
docs/getting-started/6-topical-rails/config/rails/disallowed_topics.co
docs/getting-started/7-rag/config/actions.py
docs/getting-started/7-rag/config/config.yml
docs/getting-started/7-rag/config/prompts.yml
docs/getting-started/7-rag/config/rails/blocked_terms.co
docs/getting-started/7-rag/config/rails/disallowed_topics.co

Configs were accidentally deleted

fix(docs): bring back deleted configs

---

docs/user-guides/configuration-guide.md
examples/configs/llm/deepseek-r1/config.yml
nemoguardrails/library/self_check/facts/actions.py
nemoguardrails/library/self_check/input_check/actions.py
nemoguardrails/library/self_check/output_check/actions.py
nemoguardrails/llm/filters.py
nemoguardrails/llm/prompts.py
nemoguardrails/llm/prompts/deepseek.yml
nemoguardrails/llm/providers/providers.py
nemoguardrails/llm/taskmanager.py
nemoguardrails/rails/llm/config.py
nemoguardrails/rails/llm/llmrails.py
tests/test_filters.py
tests/test_jailbreak_models.py
tests/test_llmrails_reasoning.py

Add support for reasoning models that output reasoning traces in the response (e.g. DeepSeek-R1).
Current implementation strips out the reasoning traces in the output parser for each executed Guardrails task, but different output parsers can be added to use the information in the reasoning trace as well (e.g. implement a custom rail that analyzes the reasoning traces). 
Sample model config for DeepSeek-R1 is:
```
models:
- type: main
engine: deepseek
model: deepseek-reasoner
reasoning_config:
remove_thinking_traces: True
start_token: "<think>"
end_token: "</think>"
```
Using other platforms for serving the model, such as NVIDIA AI Endpoints, is supported as long as the model name contains `deepseek` in the name. 
MR includes:
- Documentation updates
- DeepSeek-R1 prompts and sample config …

Feat: Support Models with Reasoning Traces

---

nemoguardrails/rails/llm/llmrails.py
nemoguardrails/streaming.py

Adds generation metadata per streamed token. This information can be used.
Example:
```python
from nemoguardrails import RailsConfig, LLMRails
config = RailsConfig.from_path("./examples/bots/hello_world")
config.streaming = True
rails = LLMRails(config, verbose=False)
messages = [{"role": "user", "content": "are you sure?"}]
async for chunk in rails.stream_async(messages=messages, include_generation_metadata=True):
print(f"CHUNK:{chunk}")
```
compare the output to the case when
```python
async for chunk in rails.stream_async(messages=messages, include_generation_metadata=False):
print(f"CHUNK:{chunk}")
```
```
CHUNK:Yes
CHUNK:,
CHUNK: I
CHUNK: am
CHUNK: sure
CHUNK:.
CHUNK: Is there something specific
CHUNK: you
CHUNK: would
CHUNK: like
CHUNK: me
CHUNK: to
CHUNK: assist
CHUNK: you
CHUNK: …
```

feat(streaming): add generation metadata to streaming chunks

---

nemoguardrails/actions/llm/generation.py
nemoguardrails/actions/v2_x/generation.py
tests/test_reasoning_traces.py

Resolves:
- Missed calls to `parse_task_output` cause reasoning traces to remain in output
Reproduce:
With current fix one should not see <think> </think> in result.
Prior to this fix reasoning traces are in result.
```python
from nemoguardrails.llm.filters import remove_reasoning_traces
text = "This is a <think>Some reasoning here</think> final answer."
result = remove_reasoning_traces(text, "<think>", "</think>")
print(f"Original: {text}")
print(f"Processed: {result}")
from nemoguardrails import RailsConfig, LLMRails
import yaml
config_yaml = """
models:
- type: main
engine: nim
model: deepseek-ai/deepseek-r1
reasoning_config:
remove_thinking_traces: True
start_token: "<think>"
end_token: "</think>"
"""
config = RailsConfig.from_content(yaml_content=config_yaml)
rails = LLMRails(config) …
```

fix: ensure parse_task_output is called after all llm_call invocations

---

nemoguardrails/cli/migration.py
tests/test_cli_migration.py

* Adds missing deprecated flow handling
* Accounts for different types of quote characters

Improve alpha to beta bot migration

---

nemoguardrails/library/fiddler/actions.py
tests/test_fiddler_rails.py

We recently bumped fiddler guardrails versions which made the previous version api noncompatible with the existing version. This change uses the newest fiddler guardrails api schema and fixes tests

fix: change fiddler guardrails api response definitions

---

nemoguardrails/llm/taskmanager.py
nemoguardrails/rails/llm/config.py
tests/test_reasoning_traces.py

Two minor adjustments:
- set default reasoning tokens 
- change log level to info
- add test using default ReasoningModelConfig

feat: set default start and end reasoning tokens

---

nemoguardrails/actions/llm/generation.py
nemoguardrails/rails/llm/config.py
nemoguardrails/rails/llm/llmrails.py
tests/test_streaming_output_rails.py

Refactored the conditional checks to enable output streaming configuration based on the `self.config.rails.output.streaming.enabled` flag. This change ensures that the streaming handler is correctly utilized when output streaming is enabled in the configuration.

fix: enable output rails streaming explicitly

---

nemoguardrails/llm/filters.py
nemoguardrails/llm/taskmanager.py
tests/test_llm_task_manager_multimodal.py

This PR  resolves "Prompt exceeds max length" errors, as it only changes how length is calculated without modifying the actual content. This means:
1. It correctly calculates message length by using placeholders for base64 images.
2. The actual base64 data is still preserved and sent to the LLM provider as-is.
3. If the LLM provider has its own token limits, those still apply, but that's a separate issue the user may need to handle by resizing images.
- Fix issue where large base64-encoded images in multimodal messages cause "Prompt exceeds max length" errors
- Modify `_get_messages_text_length` method to use placeholders for base64 images when calculating token length
- Add test cases to verify the fix works with various message formats
```python
import base64
import io
import logging …
```

fix: improve multimodal prompt length calculation for base64 images

---

docs/user-guides/configuration-guide.md
nemoguardrails/rails/llm/llmrails.py
nemoguardrails/utils.py
tests/test_streaming.py
tests/test_streaming_output_rails.py
tests/test_utils.py

- improve output rails error handling format when using SSE streaming
- return standard JSON error format with improved metadata for output rails violations
- enable more informative error detection and handling by server implementations
resolves https://github.com/NVIDIA/NeMo-Guardrails/issues/1032
#1012 
see nmp#745
- test streaming output rails with dummy check output config
- verify the error format is compatible with OpenAI client error handling
- test both stream_first=true and stream_first=false scenarios

feat: improve output rails error handling for SSE format

---

docs/user-guides/configuration-guide.md

Fix a code block that is showing markup.

fix(docs): remove markup from code block

---

docs/user-guides/advanced/nemoguard-topiccontrol-deployment.md

Fixes https://github.com/NVIDIA/NeMo-Guardrails/issues/1096
Fix GH-only link to a works-everwhere HTTPS link to the sample config and prompt for topic control.

chore: Add link to topic control config and prompts

---

nemoguardrails/rails/llm/llmrails.py
tests/test_tracing.py

Removes changing the response in case `tracing` is enabled.
Fixes #1093

fix: error in RunnableRails with tracing enabled

---

examples/configs/content_safety/config.yml
nemoguardrails/actions/llm/generation.py
nemoguardrails/llm/models/initializer.py
nemoguardrails/llm/models/langchain_initializer.py
nemoguardrails/llm/providers/__init__.py
nemoguardrails/llm/providers/providers.py
nemoguardrails/rails/llm/config.py
nemoguardrails/rails/llm/llmrails.py
tests/llm_providers/test_deprecated_providers.py
tests/llm_providers/test_langchain_initialization_methods.py
tests/llm_providers/test_langchain_initializer.py
tests/llm_providers/test_langchain_integration.py
tests/llm_providers/test_langchain_special_cases.py
tests/llm_providers/test_providers.py
tests/llm_providers/test_trtllm_provider.py
tests/llm_providers/test_version_compatibility.py
tests/test_configs/with_custom_chat_model/config.co
tests/test_configs/with_custom_chat_model/config.py
tests/test_configs/with_custom_chat_model/config.yml
tests/test_configs/with_custom_chat_model/custom_chat_model.py
tests/test_custom_llm.py
tests/test_providers.py

Introduces a new abstraction layer for initializing LLM models with:
- refactor providers module
- implement model initialization logic
- clear separation between text completion and chat models
- proper error handling with dedicated ModelInitializationError
- consistent provider name handling and discovery
- type safety improvements for LangChain models
Added tests, increase number of `providers` related tests from 2 to 69.
Following PRs must get merged first (those are cherry-picked to this PR)
#1084 
#1083
#1055 
#1044
#1070
#124
#902
#753 
#520
#865 
might resolve #933 
need to check #992

feat(llm): add support for langchain partner and community chat models

---

docs/user-guides/cli.md
docs/user-guides/configuration-guide.md

docs(cli): add providers fuzzy search cli command

---

nemoguardrails/library/self_check/output_check/flows.v1.co

stop needs dedent. Similar to all the other flows in guardrails library, for example see:
https://github.com/NVIDIA/NeMo-Guardrails/blob/f595d9118700afc1bd86ede77a2a24cf9a1f5208/nemoguardrails/library/self_check/input_check/flows.v1.co#L12

fix: self check output colang 1 flow

---

.github/workflows/full-tests.yml
.github/workflows/latest-deps-tests.yml
.github/workflows/test-and-build-wheel.yml
poetry.lock
pyproject.toml
tests/test_embeddings_only_user_messages.py
tests/test_sensitive_data_detection.py

It reverts poetry related changes of #1102 and make necessary changes.
- use poetry.lock prior #1102 and make minimal changes (inlcuding fastembed 0.6.0)
- fix sdd extra dependency issues 
- [remove onnxruntime from pyproject.toml as it is fastembed deps](https://github.com/NVIDIA/NeMo-Guardrails/pull/1133/commits/2ce698ea7eeb17adf6955d514bf7f96dad5768bc)
- [remove spacy from deps](https://github.com/NVIDIA/NeMo-Guardrails/pull/1133/commits/73581174a274cd6ff4de3b1df47914dc86031c52) as it is presedio_analyzer dependency
- [improve SDD setup and dependency checks](https://github.com/NVIDIA/NeMo-Guardrails/pull/1133/commits/f81c82ab97b3994c009f6e92618452cd772278d8)
- [add Python 3.13 to test distribution](https://github.com/NVIDIA/NeMo-Guardrails/pull/1133/commits/8fd0177d18f1fae3cac4f6a8e8db …

chore: fix and revert poetry lock to its stable state

---

nemoguardrails/rails/llm/config.py
tests/test_config_validation.py
tests/test_dialog_tasks.py

This PR implements a validator to ensure that reasoning traces cannot be enabled when dialog rails are present. The validator checks for both explicit dialog rails configuration and implicit dialog rails enabled through user messages, bot messages, and flows.
This change ensures that:
1. Users cannot enable reasoning traces when dialog rails are present
2. The validation covers all ways dialog rails can be enabled
3. Clear error messages guide users to resolve configuration conflicts
1. Added `check_reasoning_traces_with_dialog_rails` validator to `RailsConfig` class that:
- Checks if any model has reasoning traces enabled
- Verifies presence of dialog rails through:
- Explicit configuration in `rails.dialog`
- Implicit configuration through `user_messages`
- Implicit configuration …

feat: implement validation to forbid dialog rails with reasoning traces

---

.github/workflows/codecov.yml
.github/workflows/pr-tests.yml
.github/workflows/test-coverage-report.yml

The workflow is triggered on pushes and pull requests to the `develop` branch. Codecov integration ensures better visibility into test coverage metrics.
https://docs.codecov.com/docs/common-recipe-list

ci: add Codecov integration to workflows

---

nemoguardrails/integrations/langchain/runnable_rails.py
tests/test_runnable_rails.py

The current implementation does not support messages that have a System Message 
```python
guardrails_config = RailsConfig.from_path(<Path>)
guardrails = RunnableRails(guardrails_config)
client = ChatOpenAI(
base_url=GEN_AI_ENDPOINT,
api_key=GEN_AI_ENDPOINT_AUTHORIZATION,
model= MODEL_NAME,
temperature=0                
)
messages = [
(
"system", system
)
,(
"human", prompt
)
]
prompt = ChatPromptTemplate.from_messages(messages)
chain_with_guardrails =  prompt | (guardrails | client)
```
In this setup, `RunnableRails` does not handle messages containing system roles. Attempting to pass such a structure as a dictionary causes conflicts with the format expected by the `Runnable` interface from LangChain, which assumes a flat input structure and does not support multiple message types out of …

feat: add support for system messages to RunnableRails

---

nemoguardrails/rails/llm/llmrails.py

The `return_context` argument has been removed from the LLMRails class methods as it was deprecated. Users are encouraged to use `GenerationOptions.output_vars = True` instead. This change simplifies the interface and eliminates deprecated functionality.
BREAKING CHANGE: The `return_context` argument is no longer supported.

refactor(llmrails)!: remove deprecated return_context argument

---

nemoguardrails/rails/llm/config.py
tests/test_config_validation.py

Fixed the `has_dialog_rails` logic in `RailsConfig` to require both `user_messages` and `bot_messages` for implicit activation. Removed `flows` from the condition to align with expected behavior.
test(config): adjust tests for updated dialog rails logic
Modified test cases to reflect the corrected dialog rails activation logic.
#1137

fix(config): correct dialog rails activation logic

---

nemoguardrails/library/injection_detection/actions.py
nemoguardrails/rails/llm/config.py
tests/test_injection_detection.py

This pull request refactors and enhances the injection detection module by improving configuration validation, supporting inline YARA rules, and adding new tests. The changes aim to make the code more modular, robust, and easier to extend.
* Renamed `_validate_unpack_config` to `validate_injection_config` and updated it to focus solely on validating the configuration without unpacking values. [[1]](diffhunk://#diff-2e8e7fb15761a3d7ce33b9010d2c4e1c7ae19dc092a5747dfeb1c70653695219L48-L62) [[2]](diffhunk://#diff-2e8e7fb15761a3d7ce33b9010d2c4e1c7ae19dc092a5747dfeb1c70653695219R67-R81)
* Introduced `extract_injection_config` to handle the extraction and processing of configuration values, separating concerns for better modularity.
* Enhanced validation logic for `action_option` and `yara_path` …

feat: add inline YARA rules support

---

nemoguardrails/rails/llm/config.py
tests/test_config_validation.py

Refactors the dialog rails validation logic to properly respect the embeddings_only flag, allowing reasoning traces to be enabled when this flag is set to True. Adds tests to verify this behavior.
related to #1161 and #1137

fix: allow reasoning traces when embeddings_only is True

---

nemoguardrails/llm/taskmanager.py
tests/test_llm_task_manager.py

This change addresses an issue where reasoning traces from previous bot messages were included in the prompt history for subsequent LLM calls when rails.output.apply_to_reasoning_traces=true was enabled.
The fix adds event preprocessing in LLMTaskManager to strip reasoning traces from both BotMessage.text and StartUtteranceBotAction.script fields before including them in prompt rendering, preventing the LLM from seeing its own internal reasoning from previous turns.
Comprehensive tests were added to verify:
Preprocessing doesn't modify original events
Reasoning traces are properly removed from prompt history
The clean bot messages are still included in rendered prompt

feat: prevent reasoning traces from contaminating LLM prompt history

---

docs/user-guides/configuration-guide.md
examples/configs/llm/deepseek-r1/config.yml
nemoguardrails/llm/taskmanager.py
nemoguardrails/rails/llm/config.py
tests/test_config_validation.py
tests/test_llmrails_reasoning_output_rails.py
tests/test_reasoning_traces.py

Renamed `remove_thinking_traces` to `remove_reasoning_traces` across the codebase for consistency. Added a deprecated field `remove_thinking_traces` with a warning to ensure backward compatibility.
- Updated documentation, tests, and configurations.
- Added a model validator to handle deprecated field usage.
- Issued deprecation warnings when `remove_thinking_traces` is used.
BREAKING CHANGE: Configurations using `remove_thinking_traces` must migrate to `remove_reasoning_traces` from 0.15.0.

feat(config): rename `remove_thinking_traces`

---

docs/user-guides/configuration-guide.md

Clarify the purpose of the `models.model.parameters` field.
Fixes https://github.com/NVIDIA/NeMo-Guardrails/issues/1124

docs: clarify purpose of model parameters field in configuration guide

---

docs/user-guides/advanced/streaming.md

Originally, I thought the pre-0.13.0 streaming information was obsolete.  I've since learned that there's streaming with output rails and without output rails.  I do not know the details of how streaming works without output rails, but it was important to remove the statement that streaming is not supported with output rails.

docs: Output rails are supported with streaming

---

nemoguardrails/library/injection_detection/actions.py
nemoguardrails/library/injection_detection/flows.co
nemoguardrails/library/injection_detection/flows.v1.co
tests/test_injection_detection.py

- implement RailException for injection detection (a must have for checks)
- Add TypedDict for structured return values
- improve error handling for malformed YARA rules
This pull request enhances the injection detection system by introducing a structured return type, improving error handling, and adding new tests for edge cases. The changes aim to make the system more robust and easier to integrate into workflows.
* Introduced a `TypedDict` named `InjectionDetectionResult` to standardize the return type for injection detection functions, containing `is_injection`, `text`, and `detections` fields. (`nemoguardrails/library/injection_detection/actions.py`, [nemoguardrails/library/injection_detection/actions.pyR52-R57](diffhunk://#diff-2e8e7fb15761a3d7ce33b9010d2c4e1c7ae19dc092a5747dfeb1c7065 …

feat: add RailException support and improve error handling

---

poetry.lock

resolves https://github.com/NVIDIA/NeMo-Guardrails/security/dependabot/89

chore(deps): bump h11 from 0.14.0 to 0.16.0

---

nemoguardrails/rails/llm/llmrails.py
tests/test_llm_rails_context_variables.py

This PR addresses an issue where `self.explain_info` could be overwritten during calls to `stream_async`, potentially leading to incomplete explanation data.
The root cause was that the `generate_async` task and the `_run_output_rails_in_streaming` function (if output streaming rails were active) could independently initialize `ExplainInfo` objects if the `explain_info_var` context variable was not set prior to the `generate_async` task's creation.
The fix ensures that `explain_info_var` and `self.explain_info` are initialized at the beginning of the `stream_async` method. This guarantees that both the `generate_async` task (via context variable inheritance) and `_run_output_rails_in_streaming` use the same `ExplainInfo` instance, preserving data integrity.
[same as …

fix: Prevent explain_info overwrite during stream_async

---

nemoguardrails/rails/llm/config.py

This pull request makes several updates to the `nemoguardrails/rails/llm/config.py` file, focusing on improving deprecation handling, updating field configurations, and enhancing clarity in the codebase. The changes include replacing deprecated warnings with silent migrations, modifying field types, and cleaning up imports.
* Replaced the deprecated warning for the `remove_thinking_traces` field with a silent migration to the `remove_reasoning_traces` field in the `_migrate_thinking_traces` method. This simplifies the user experience by automatically propagating values without issuing warnings.
* Updated the `remove_thinking_traces` field to include a `deprecated` attribute in its description, improving clarity on its deprecation status.
* Changed the `apply_to_reasoning_traces` field in …

refactor(config): update deprecated field handling for remove_thinking_traces

---

tests/test_streaming_handler.py

Improves coverage of streaming.py by 15% from [85.2](https://app.codecov.io/gh/NVIDIA/NeMo-Guardrails/commit/e96802f0f11f12630c2764e9bd4f8a6d6168f16c/blob/nemoguardrails/streaming.py?dropdown=coverage) to [97.89](https://app.codecov.io/gh/NVIDIA/NeMo-Guardrails/commit/821c9ef053f8c2e83ed47c8bf9e3c64fc06eed56/blob/nemoguardrails/streaming.py?dropdown=coverage)
- Added tests for various functionalities of StreamingHandler, including:
- Piping streams between handlers
- Buffering enable/disable behavior
- Handling multiple stop tokens
- Metadata inclusion and processing
- Suffix and prefix pattern handling
- Edge cases for __anext__ method
- First token handling and generation info
- Improved test coverage for async methods and error scenarios.
- Addressed potential issues with streaming …

test(streaming): add extensive tests for StreamingHandler to enhance coverage

---

nemoguardrails/rails/llm/llmrails.py
nemoguardrails/streaming.py
tests/test_streaming_handler.py

This PR resolves #1184 by  introducing END_OF_STREAM sentinel and update streaming handling.
- Replaced inconsistent use of `None` and `""` for stream termination
in `StreamingHandler` with a dedicated `END_OF_STREAM` sentinel object.
- Modified `push_chunk` to convert `None` to `END_OF_STREAM`.
- Updated `__anext__` to raise `StopAsyncIteration` only for `END_OF_STREAM`
and to return empty strings or dicts with empty/None text as data.
- Adjusted `_process` to correctly handle `END_OF_STREAM` for buffering
and queueing logic.
- Updated `on_llm_end` to use `END_OF_STREAM`.
- Revised tests in `test_streaming_handler.py` to reflect these changes,
including how empty first tokens are handled and how `__anext__` behaves
with various inputs.
requires:

refactor(streaming): introduce END_OF_STREAM sentinel and update handling

---

examples/configs/nemotron/README.md
examples/configs/nemotron/config.yml
nemoguardrails/llm/prompts.py
nemoguardrails/llm/prompts/llama3.yml
nemoguardrails/llm/prompts/nemotron_reasoning.yml
nemoguardrails/rails/llm/llmrails.py
tests/test_nemotron_prompt_modes.py
tests/test_system_message_conversion.py

This PR adds support for Nemotron models in NeMo Guardrails with a message-based prompt approach. It implements a system for controlling detailed thinking traces both for internal tasks and in final user responses, similar to how it works on [build.nvidia.com.](https://build.nvidia.com/)
- Added new `nemotron.yml` with message-based prompt templates
- Implemented "detailed thinking on" system messages for complex reasoning tasks
- Added system message handling in LLMRails to control thinking traces
- Provided example configuration in examples/configs/nemotron
As Nemotron is a hybrid reasoning model, users can toggle the "detailed thinking" feature for final responses:
```python
response = rails.generate(messages=[
{"role": "system", "content": "detailed thinking on"}, 
{"role": "user", …
```

feat: add Nemotron model support with message-based prompts

---

CONTRIBUTING.md

Got a new computer.  I had to install packages to make progress.  I'm OK with ditching this PR if it's either A) obvious, or B) only me.

chore: Identify OS packages to intstall

---

docs/getting-started/5-output-rails/README.md
docs/user-guides/configuration-guide.md

Fix some issues on output streaming rails documentation.
Specifically the `streaming.enabled` field was missing
I haven't opened a proper issue for that

docs: fix output rail doc

---

docs/conf.py
docs/index.md
docs/release-notes.md

Add release notes so that recent additions to this large set of HTML pages are more findable.

docs: Add release notes

---

docs/conf.py

We need to increase the number of heading levels that are possible targets so that the RNs can link to the headings.
This fixes a goof in the [RNs](https://nvidia.github.io/NeMo-Guardrails/review/pr-1228/release-notes.html) where the "Added the rails.output.apply_to_reasoning_traces field" bullet did not end with a link _at all_.

fix: More heading levels so RNs resolve links

---

nemoguardrails/rails/llm/llmrails.py
tests/test_llama_guard.py
tests/test_llmrails.py
tests/test_patronus_lynx.py

This PR addresses an issue where the configuration for other models (e.g., content safety, topic control) was not being honored when a main model was provided via the LLMRails (or RunnableRails) constructor. The changes ensure that all model configurations are properly initialized and accessible, even when a main model is injected.
Fixes #1220

fix: constructor LLM should not skip loading other config models

---

nemoguardrails/library/content_safety/actions.py

hiii NVidia!
this one-line PR fixes an issue with the `rails.stream_async` example in the "Getting Started" docs. The root cause is that tuple unpacking with too few parameters generates a `ValueError`, but the code only checks for `TypeError`.
This change is enough to get the docs example working.
To reproduce, install `v0.13.0` of this library, make sure you have a valid API key in the environment, and run their example:
```
import asyncio
from nemoguardrails import LLMRails, RailsConfig
config = RailsConfig.from_path("./config")
rails = LLMRails(config)
async def stream_response(messages):
async for chunk in rails.stream_async(messages=messages):
print(chunk, end="")
print()
messages=[{
"role": "user",
"content": "Tell me a five-step plan to rob a bank."
}] …
```

fix(content_safety): replace try-except with iterable unpacking for policy violations

---

nemoguardrails/library/jailbreak_detection/requirements.txt

The Docker build for the jailbreak detection heuristics server was failing with a binary incompatibility error:
```
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
This error occurred during the step that pre downloads the GPT-2 model, when the transformers library tried to import scikit-learn, which had been compiled against a different version of numpy than what was present at runtime.
- The `requirements.txt` had `scikit-learn==1.2.2` pinned but no explicit numpy version constraint
- during Docker build transformers and other deps pulled in a newer version of numpy
- scikit-learn 1.2.2 was compiled against numpy 1.23.x series, but a newer numpy version was installed
- this created a binary incompatibility …

fix(jailbreak): pin numpy==1.23.5 for scikit-learn compatibility

---

nemoguardrails/library/self_check/facts/actions.py
nemoguardrails/library/self_check/input_check/actions.py
nemoguardrails/library/self_check/output_check/actions.py
nemoguardrails/llm/output_parsers.py
tests/test_content_safety_integration.py
tests/test_content_safety_output_parsers.py

Content safety actions were failing due to output parser interface incompatibility. The parsers returned `Tuple[bool, List[str]]` format, but actions used starred unpacking syntax `is_safe, *violated_policies = result` which expected list format.
Multiple bugs in output parsers:
1. **Iterable Unpacking Bug**: Tuple format `(True, [])` incompatible with `is_safe, *violated_policies = result` that is introduced in #1207 
2. **Empty Violations Bug**: Returned `[""]` instead of `[]` for no violations
3. **Case Sensitivity Bug**: Violations converted to lowercase, losing original case (`"s1"` vs `"S1"`)
-  **Changed return type**: `Tuple[bool, List[str]]` → `Sequence[Union[bool, str]]`
-  **Fixed starred unpacking**: Now returns `[True]` or `[False, "policy1", "policy2"]` format
-  **Preserved …

fix(output_parsers): iterable unpacking compatibility in content safety parsers

---

nemoguardrails/rails/llm/llmrails.py
tests/test_llmrails.py

When the main LLM is initialized from configuration (without providing an LLM via constructor), it was not being registered as an action parameter. This caused actions that depend on the `llm` parameter to receive `None` instead of the actual LLM instance, leading to runtime errors.
**Error example:**
```
AttributeError: 'NoneType' object has no attribute 'agenerate_prompt'
```
This affected built in actions like `self_check_input` and any custom actions that require the `llm` parameter.
In the `_init_llms()` method, when initializing the main LLM from config, the code was setting `self.llm` but missing the call to register it as an action parameter:
```python
self.llm = init_llm_model(...)
```
Added the missing `register_action_param("llm", self.llm)` call after initializing the main LLM …

fix: register main LLM as action parameter when initialized from config

---

examples/configs/jailbreak_detection_nim/README.md
examples/configs/jailbreak_detection_nim/config.yml
nemoguardrails/library/jailbreak_detection/actions.py
nemoguardrails/rails/llm/config.py
tests/test_jailbreak_config.py

This change adds a new optional field `api_key` to the `JailbreakDetectionConfig` Pydantic model. This allows customers to provide an API Key in a RailsConfig object or YAML file, for use in Jailbreak NIM calls. Prior to this change, the `api_key_env_var` field used an environment variable (for example NVIDIA_API_KEY) to get the API Key for the Jailbreak NIM.
A new config is included in the PR (examples/configs/jailbreak_detection_nim) used to integration test this locally. By setting the NVCF API key in the main model's `parameters.api_key` field, and in the Jailbreak model's `api_key` field, API keys can be injected programmatically without setting the `NVIDIA_API_KEY` environment variable.
The test plan below validates the main model and Jailbreak NIM API Keys are being used by …

feat(jailbreak): Add direct API key configuration support

---

CHANGELOG.md
README.md
pyproject.toml

Update version to 0.14.1 and add changelog entries for the new release.

bump: release v0.14.1

---

docs/index.md
docs/user-guides/advanced/index.rst

Fix the advanced jailbreak deployment doc to appear

docs: fix page-not-appearing issue

---

nemoguardrails/rails/llm/buffer.py
nemoguardrails/rails/llm/llmrails.py
tests/test_buffer_strategy.py
tests/test_streaming.py

The test `test_sequential_streaming_output_rails_allowed` was failing with words being concatenated without spaces:
```
AssertionError: assert 'compliant high quality' in 'This is a safeand complianthigh qualityjoke thatshould passall checks.'
```
The issue was in `_run_output_rails_in_streaming` method in `llmrails.py`. The method was calling `chunk_str_rep.split()` which removed all whitespace, then tried to reconstruct spacing with `f" {word}"`, but this lost the original token format including trailing spaces.
This created a design contradiction: the buffer strategy creates multi-word chunks (e.g., `"This is a funny "`, `"joke but "`) for efficient output rails processing, but then the code immediately split these back into individual words, defeating the purpose.
The fix was to **not …

fix(streaming): resolve word concatenation in streaming output rails

---

examples/configs/tracing/README.md
examples/configs/tracing/working_example.py
nemoguardrails/tracing/adapters/opentelemetry.py
poetry.lock
pyproject.toml
tests/test_tracing_adapters_opentelemetry.py

This PR refactors the OpenTelemetry integration to follow OpenTelemetry best practices by removing the SDK dependency and relying only on the OpenTelemetry API. We should not configure observability; that's the application's responsibility.
- **Breaking**: Removed `opentelemetry-sdk` from `[tracing]` extra dependencies
- **Breaking**: OpenTelemetry adapter no longer configures SDK/exporters via YAML config
- Added deprecation warnings for old configuration parameters (`exporter`, `resource_attributes`, etc.)
- Added validation to warn users when OpenTelemetry is not properly configured
- Kept `register_otel_exporter` function with deprecation warning (will be removed in v0.16.0)
Resolves #1094

feat(tracing)!: update tracing to use otel api

---

nemoguardrails/colang/runtime.py
nemoguardrails/colang/v1_0/runtime/runtime.py
nemoguardrails/rails/llm/config.py
nemoguardrails/rails/llm/llmrails.py
tests/test_parallel_streaming_output_rails.py

This PR implements streaming for parallel output rails execution
- Add _run_output_rails_in_parallel_streaming method to run output rails concurrently
- Use asyncio tasks to execute multiple rails simultaneously during streaming
- Implement early termination when any rail blocks content to optimize performance
- Register the new action in the runtime dispatcher
- Add proper error handling and cancellation for robust parallel execution
- Avoid full flow state management issues that can occur with hide_prev_turn logic during streaming
- Add comprehensive tests for parallel streaming functionality
requires #1259

feat: implement parallel streaming output rails execution

---

docs/user-guides/advanced/streaming.md
nemoguardrails/rails/llm/llmrails.py
tests/test_streaming_output_rails.py

Add ability to pass custom async token generators to `stream_async`, enabling integration with external LLMs or custom streaming sources. Update docs and add tests for output rails interaction and edge cases with external generators.
Note:
* This is equivalent to output rails only option in streaming mode. 
* Useful for testing streaming with output rails feature

feat(streaming): support external async token generators

---

nemoguardrails/colang/runtime.py
nemoguardrails/colang/v1_0/runtime/flows.py
nemoguardrails/colang/v1_0/runtime/runtime.py
nemoguardrails/logging/processing_log.py
nemoguardrails/rails/llm/config.py
nemoguardrails/rails/llm/llm_flows.co
nemoguardrails/rails/llm/llmrails.py
tests/test_configs/parallel_rails/actions.py
tests/test_configs/parallel_rails/config.yml
tests/test_configs/parallel_rails/prompts.yml
tests/test_configs/parallel_rails/rails/blocked_terms.co
tests/test_parallel_rails.py

This MR enables parallel input/output rail execution (in Colang 1) through a new action called 'run_flows_in_parallel'.
- Input and output rails can be configured to run in parallel through a new field in the bot config (parallel: True).
- Two additional actions are added (`run_input_rails_in_parallel`, `run_output_rails_in_parallel`) to simplify the parallel rails calling and to create the necessary tracing events: `StartInputRail`, `InputRailFinished`, `StartOutputRail`, `OutputRailFinished`.
- The parallel rail execution tries to mimic the sequential processing as much as possible. Therefore, the resulting event history, processing log and flow context will be almost the same and appear in sequential order, even if the event timestamps reveal the concurrent execution of the rails.

feat: parallel rails execution

---

.github/workflows/release.yml

Install git cliff from source due to following issue:
```
kenji-miyake/setup-git-cliff@v2 is not allowed to be used in NVIDIA/NeMo-Guardrails. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace, or matching the following: BSFishy/pip-action@v1, EndBug/add-and-commit@*, EnricoMi/publish-unit-test-result-action@*, JamesIves/github-pages-deploy-action@*, Jimver/cuda-toolkit@*, NVIDIA/blossom-action@*, NVIDIA/gitlab-answer-app/*, NVIDIA/spark-rapids-common@*, SonarSource/sonarqube-scan-action@*, TreTuna/sync-branches@1.4.0, Wandalen/wretry.action/post@*, abbbi/github-actions-tune@*, actions-cool/pr-approve@v0.0.1-beat, actions-ecosystem/action-add-assignees@v1, …
```

ci(release): install git-cliff manually for workflow

---

nemoguardrails/colang/v1_0/runtime/runtime.py
tests/test_internal_error_parallel_rails.py

Add a "BotIntent" event with intent "stop" to the event list after an internal error occurs. This prevents further LLM generation and ensures execution halts appropriately following an error.
please run https://gist.github.com/Pouyanpi/eef2a71efc16fe6976f8e15db91717cf against develop branch and after this fix.
This demonstrates the fix using a configuration which has:
- Parallel input rails: content safety + self check
- Parallel output rails: content safety + self check
- NIM models for content safety
PROBLEM (Before Fix):
- each failing rail generates 'I'm sorry, an internal error has occurred.'
- with 4 rails, user could see 4 error messages
SOLUTION (After Fix):
- first error generates BotIntent stop event
- stop event cancels remaining rails
- user sees only one error message

fix(runtime): stop execution after internal error

---

nemoguardrails/rails/llm/llmrails.py
tests/test_tracing.py

Using tracing overrides all user-provided logging configuration. While this is necessary to generate detailed logs, it should not require _returning_ that new log information back to the user if they did not request it. See https://github.com/NVIDIA/NeMo-Guardrails/issues/1316 for more detail.
Changes:
1) Ensures that regardless of tracing configuration, the returned response object respects the requested log options.
2) Modifies existing tracing unit test to account for new logging behavior
3) Adds new tracing unit test to check that ll permutations of logging options are respected if tracing is configured. 
- Implements #1316

fix: respect the user-provided log options regardless of tracing configuration

---

docs/conf.py
docs/index.md
docs/user-guides/advanced/kv-cache-reuse.md

Add documentation for kv cache reuse for NemoGuard NIMs.

docs: add kv cache reuse documentation

---

nemoguardrails/rails/llm/llmrails.py
tests/test_llmrails.py

Return `self` from the `register_*` methods in the LLMRails class to allow for function chaining, allows for structuring the code in a more functional way:
Before:
```py
rails = LLMRails(
config=config,
llm=azure_openai,
)
rails.register_action(proxy, "proxy")
rails.register_action(fetch_updated_guidelines, "fetch_updated_guidelines")
```
After:
```py
rails = (
LLMRails(
config=config,
llm=azure_openai,
)
.register_action(proxy, "proxy")
.register_action(fetch_updated_guidelines, "fetch_updated_guidelines")
)
```
Note that the `Before` version is still possible, this change would just allow for more flexible structure.

feat: support method chaining by returning `self` from LLMRails.register_* methods

---

nemoguardrails/library/topic_safety/actions.py
tests/test_topic_safety_internalevent.py

Fixes `TypeError` when using topic safety rails with Colang 2.0 configurations.
When running topic safety checks in Colang 2.0, the `topic_safety_check_input` action would fail with:
TypeError: 'InternalEvent' object is not subscriptable
This occurred because Colang 2.0 passes `InternalEvent` objects to the action, but the code was trying to pass them directly to `to_chat_messages()` which expects dictionary events.
- Convert `InternalEvent` objects to dictionary format before passing to `to_chat_messages()`
- Maintain backward compatibility with dictionary events
- Follows separation of concerns by keeping the conversion logic in the topic safety action
- Added regression test that fails without the fix and passes with it
- Verified fix works with content safety v2 example configuration …

fix(topic_safety): handle InternalEvent objects in topic safety actions for Colang 2.0

---

docs/user-guides/community/pangea.md
docs/user-guides/guardrails-library.md
docs/user-guides/llm-support.md
examples/configs/pangea/README.md
examples/configs/pangea/config.yml
examples/configs/pangea_v2/README.md
examples/configs/pangea_v2/config.yml
examples/configs/pangea_v2/main.co
examples/configs/pangea_v2/rails.co
examples/configs/pangea_v2_no_llm/config.yml
examples/configs/pangea_v2_no_llm/main.co
examples/configs/pangea_v2_no_llm/rails.co
nemoguardrails/library/pangea/__init__.py
nemoguardrails/library/pangea/actions.py
nemoguardrails/library/pangea/flows.co
nemoguardrails/library/pangea/flows.v1.co
nemoguardrails/rails/llm/config.py
tests/test_pangea_ai_guard.py

Adds a new community integration, Pangea AI Guard, to NeMo Guardrails.
@Pouyanpi

feat: add Pangea AI Guard community integration

---

nemoguardrails/rails/llm/llmrails.py
nemoguardrails/rails/llm/utils.py
tests/test_llm_isolation.py
tests/test_llm_isolation_e2e.py
tests/test_llmrails.py
tests/test_llmrails_reasoning.py
tests/test_rails_llm_utils.py

Update isolated LLM creation to only target actions defined in rails config flows. This ensures that LLMs are not unnecessarily created for actions not present in the configuration. Adds comprehensive tests to verify correct behavior, including handling of empty configs and skipping already-registered LLMs.

feat(llmrails): isolate LLMs only for configured actions

---

docs/index.md
docs/user-guides/advanced/nemotron-content-safety-multilingual-deployment.md

Reviewers requested a soup-to-nuts experience with Guardrails and the content safety multilingual NIM.
Review HTML: https://nvidia.github.io/NeMo-Guardrails/review/pr-1354/user-guides/advanced/nemotron-content-safety-multilingual-deployment.html
@miyoungc, if you could look this PR over first and let me know anything you'd like changed, that'd be great.
I tagged @tgasser-nv as a Guardrails SME, but I'm OK with whomever @cparisien can spare for a few minutes.
After eng SME review, I'll ask Zhenming if he can eventually find cycles to review for this unplanned work.

docs: Integrate with multilingual NIM

---

nemoguardrails/llm/models/langchain_initializer.py

suppress langchain_nvidia_ai_endpoints warnings
```sh
irtualenvs/nemoguardrails-O6aG79rF-py3.12/lib/python3.12/site-packages/langchain_nvidia_ai_endpoints/_common.py:212: UserWarning: Found nvidia/llama-3.1-nemoguard-8b-content-safety in available_models, but type is unknown and inference may fail.
warnings.warn(
/Users/prezakhani/Library/Caches/pypoetry/virtualenvs/nemoguardrails-O6aG79rF-py3.12/lib/python3.12/site-packages/langchain_nvidia_ai_endpoints/_common.py:212: UserWarning: Found nvidia/llama-3.1-nemoguard-8b-topic-control in available_models, but type is unknown and inference may fail.
warnings.warn(
```

fix(models): suppress langchain_nvidia_ai_endpoints warnings

---

nemoguardrails/library/jailbreak_detection/request.py
tests/test_jailbreak_request.py

Fix URL joining in NIM jailbreak detection to handle base URLs with/without trailing slashes and classification paths with/without leading slashes.
- Add `join_nim_url()` helper function
- Update `jailbreak_nim_request()` to use normalized URL joining
- Add comprehensive tests covering all slash combinations

fix(jailbreak): handle URL joining with/without trailing slashes

---

.github/workflows/test-coverage-report.yml

Remove branch restriction from pull_request trigger to allow codecov coverage reporting on PRs targeting any branch, not just develop.

ci: enable codecov for all pull requests

---

nemoguardrails/actions/llm/utils.py
nemoguardrails/context.py
nemoguardrails/rails/llm/llmrails.py
nemoguardrails/rails/llm/options.py
tests/rails/llm/test_options.py
tests/test_tool_calling_passthrough_integration.py
tests/test_tool_calling_utils.py
tests/test_tool_calls_context.py

This PR implements tool call extraction and passthrough functionality in LLMRails, enabling the framework to capture and forward tool calls from LLM responses. Key changes include:
- Add tool_calls_var context variable for storing LLM tool calls
- Refactor llm_call utils to extract and store tool calls from responses
- Support tool calls in both GenerationResponse and dict message formats
- Add ToolMessage support for langchain message conversion
- Comprehensive test coverage for tool calling integration scenarios
The implementation maintains backward compatibility while adding new tool calling capabilities to the passthrough mode.

feat(tool-calling): add tool call passthrough support in LLMRails

---

nemoguardrails/integrations/langchain/runnable_rails.py
tests/runnable_rails/test_basic_operations.py
tests/runnable_rails/test_batch_as_completed.py
tests/runnable_rails/test_batching.py
tests/runnable_rails/test_composition.py
tests/runnable_rails/test_format_output.py
tests/runnable_rails/test_history.py
tests/runnable_rails/test_piping.py
tests/runnable_rails/test_runnable_rails.py
tests/runnable_rails/test_streaming.py
tests/runnable_rails/test_tool_calling.py
tests/runnable_rails/test_transform_input.py
tests/runnable_rails/test_types.py
tests/utils.py

- Complete rewrite of RunnableRails implementing full LangChain Runnable protocol
- Added comprehensive async/sync support for invoke, batch, and streaming operations
- Enhanced input/output handling for all LangChain message formats and chaining scenarios
- Extensive test suite with 14 test files covering batching, streaming, tool calling, and composition
requires #1364 and #1343 and #1289

feat(runnable-rails): update RunnableRails with full LangChain Runnable protocol support

---

nemoguardrails/actions/llm/utils.py
nemoguardrails/context.py
nemoguardrails/integrations/langchain/runnable_rails.py
nemoguardrails/rails/llm/llmrails.py
nemoguardrails/rails/llm/options.py
tests/runnable_rails/test_metadata.py
tests/runnable_rails/test_runnable_rails.py

Ensure AIMessage responses from RunnableRails contain the same metadata fields (response_metadata, usage_metadata, additional_kwargs, id) as direct LLM calls, enabling consistent LangChain integration behavior.

feat(runnable-rails): implement AIMessage metadata parity in RunnableRails

---

nemoguardrails/integrations/langchain/runnable_rails.py
tests/runnable_rails/test_metadata.py
tests/runnable_rails/test_streaming.py

Enhance streaming in RunnableRails to include generation metadata in streamed chunks. Skips END_OF_STREAM markers and updates chunk formatting to support metadata for AIMessageChunk outputs. This improves compatibility with consumers expecting metadata in streaming responses.

feat(runnable-rails): stream metadata in RunnableRails output

---

nemoguardrails/actions/llm/generation.py
nemoguardrails/actions/llm/utils.py
nemoguardrails/rails/llm/config.py
nemoguardrails/rails/llm/llm_flows.co
nemoguardrails/rails/llm/llmrails.py
nemoguardrails/rails/llm/options.py
tests/runnable_rails/test_tool_calling.py
tests/test_bot_tool_call_events.py
tests/test_output_rails_tool_calls.py
tests/test_tool_calling_passthrough_integration.py
tests/test_tool_calling_passthrough_only.py
tests/test_tool_calls_event_extraction.py
tests/test_tool_output_rails.py

Introduce tool output/input rails configuration and Colang flows for tool call validation and parameter security checks. Add support for BotToolCall event emission in passthrough mode, enabling tool call guardrails before execution.
must be merged after #1370 #1369 #1366

feat(tool-rails): add support for tool output rails and validation

---

nemoguardrails/library/jailbreak_detection/requirements.txt

Bump transformers to >=4.56.0 and torch to >=2.8.0 to resolve high severity vulns

chore(jailbreak-detection): update transformers and torch

---

nemoguardrails/logging/callbacks.py
tests/test_callbacks.py

Previously, messages of type "tool" were not distinctly labeled in the LoggingCallbackHandler output, causing them to be grouped under "System".
This change adds explicit handling for "tool" messages, labeling them as "Tool" in the logs for improved clarity and debugging.

fix(logging): add "Tool" type to message sender labeling

---

nemoguardrails/actions/action_dispatcher.py
nemoguardrails/actions/actions.py
nemoguardrails/actions/core.py
nemoguardrails/actions/langchain/safetools.py
nemoguardrails/actions/llm/generation.py
nemoguardrails/actions/llm/utils.py
nemoguardrails/actions/retrieve_relevant_chunks.py
nemoguardrails/actions/summarize_document.py
nemoguardrails/actions/v2_x/generation.py
nemoguardrails/actions/validation/base.py
nemoguardrails/actions/validation/filter_secrets.py
nemoguardrails/context.py
nemoguardrails/rails/llm/config.py
pyproject.toml
tests/test_action_dispatcher.py
tests/test_general_instructions.py
tests/test_tool_calling_utils.py
tests/v2_x/test_passthroug_mode.py

Nemo Guardrails doesn't have type-checking enforced in the project today. This PR will be used to compile type-cleaning related to the `nemoguardrails/actions` module prior to merging into the top-level type-cleaning [PR1367](https://github.com/NVIDIA/NeMo-Guardrails/pull/1367). 
Prior to this work the `actions` module had 189 errors, 0 warnings, and 0 informations.

chore(types): Type-clean /actions (189 errors)

---

docs/index.md
docs/user-guides/advanced/index.rst
docs/user-guides/advanced/tools-integration.md

Add "Tools Integration" guide to the advanced user documentation. The new guide covers supported tools, configuration settings (including passthrough mode), implementation examples, and security considerations for tool usage in NeMo Guardrails. Also update the advanced index to include the new guide.

docs: add tools integration guide

---

docs/user-guides/advanced/tools-integration.md

Completed the incomplete "Integration with RunnableRails" section in the tools integration guide by adding references to both LangChain and LangGraph integration guides.

 docs(tools): fix RunnableRails integration section with references
